### ISSUE TITLE
Where  i can make routes file 

### ISSUE THREAD

**Issue by dualsyscornd** [daveh/php-mvc#102]
please explain me

**Comment by daveh** [comment]
In this framework the routes are defined in the [public/index.php](https://github.com/daveh/php-mvc/blob/master/public/index.php#L28) file.

**Comment by robertaonnis** [comment]
Hello,
if i insert all the route that i have like: 
$router->add('', ['controller' => 'Product', 'action' => 'index']);

and i digit localhost/route show me an issue that the route not exist. but fore sure exist.

**Comment by daveh** [comment]
@robertaonnis The route you added above would match the homepage, e.g. http://localhost/

**Comment by robertaonnis** [comment]
Yes i Really sorry, I have read all the code yesterday and solve
