### ISSUE TITLE
url problem

### ISSUE THREAD

**Issue by ianims** [daveh/php-mvc#103]
I am trying to add urls with the following form:
site.com/process/view/345/some_text
site.com/process/view/876/some_other_text

so the last two parameters vary.I have tried:
$r->add( 'process/{action}/{id:}/{lang:[a-z]{2}+}')
and also :
$r->add( 'process/{action}/{id:}/{name:}')
but it always seems to fail at the preg_match

thanks

**Comment by daveh** [comment]
You need a regex that includes an underscore to match those segments (plus your id variable is missing the regex). Try this:

`$r->add( 'process/{action}/{id:\d+}/{name:[a-z_]+}')
`

**Comment by ianims** [comment]
ok now working ok thanks
