### ISSUE TITLE
add pdfdom to framework

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#104]
Hi dave, how are you?  

i have a question to you, if you can answer that, i`ll be realy graitful  

And the question is ....
¿How is the correct way to add de DomPdf library to the framework?

I just run **composer require dompdf/dompdf** in the app directory and composer install the library in vendor/dompdf, and i try to access from a an app controller in this way but its not working:

`
```
<?php

namespace App\Controllers;

use \Core\View;
use \App\Config;
use \Dompdf\Dompdf;

class Escritos extends \Core\Controller
{
    public function generarPDF () 
    {

         // instantiate and use the dompdf class
	$dompdf = new Dompdf();
     }
}
```
`
**that give a:**

**Fatal error**
**Uncaught exception: 'Error'**

**Message: 'Class 'Dompdf\Dompdf' not found'**

greatings!

**Comment by raleandri** [comment]
just running **composer require dompdf/dompdf** in the app directory ?

**Comment by daveh** [comment]
Hi - you have to run the **composer require** command in the root folder, not the App folder - that way the package will be included in the vendor folder in the root, and including Composer's autoloader in the front controller will include the package's files  automatically.
