### ISSUE TITLE
Struggling with redirects after form submission 

### ISSUE THREAD

**Issue by matats** [daveh/php-mvc#107]
Hello Dave
I am trying to practice my mvc skills using your framework but am now stuck.
Upon form submission, records get into db but I cannot figure out how to redirect to another "Submission successful" page. I hope you can help me. Thanx in advance.
Here is my current code:
**Posts controller**
` /**
  * Show new post form
  */
  public function newAction() {
      View::renderTemplate('posts/new.html');
  }
  /**
  * Create the post
  */
  public function createAction() {
    $post = new Post($_POST);
        if ($post->add()) {
            $this->redirect('/posts/success');
        } else {
            View::renderTemplate('posts/new.html', [
                'post' => $post
            ]);
        }
  } 
  /**
  * Show the submission success page
  */
    public function successAction()
    {
        View::renderTemplate('posts/success.html');
    }`
**My Posts Model**
`public function add() {
        try {
            $db = static::getDBPosts();
            $stmt = $db->prepare("INSERT INTO posts (userId, title, slug, body,) VALUES (:userId, :title, :slug, :body)");            
            $stmt->bindParam(':userId', $_REQUEST['userId']);
            $stmt->bindParam(':title', $_REQUEST['title']);
            $stmt->bindParam(':slug', $_REQUEST['slug']);
            $stmt->bindParam(':body', $_REQUEST['body']);
            $stmt->execute();        
            echo "Post created successfully";        
         }catch(PDOException $e) {
            echo $e->getMessage();
         }
     }`
**The html form**
<form action="/posts/createPost" id="newPost">
    <input type="text" placeholder="Title" name="title" value="{{ blog.title }}">
    <input type="text" placeholder="slug" name="slug" value="{{ blog.slug }}">
    <textarea name="body" id="body" cols="30" rows="10"></textarea>
    <input type="hidden" placeholder="userId" name="userId" value="{{ user.id }}">
    <input type="hidden" placeholder="status" name="status" value="1">
    <button type="submit">Create</button>

**Comment by daveh** [comment]
That looks like it should work. What happens when you try it? Do you get any error messages? What URL is shown in the browser?

**Comment by matats** [comment]
Thanx for getting back to me.
After submission I get taken back to the form, but the succesful message from controller is displayed. The data is saved correctly in the db.
The url shows the action posts/createPost
I wonder if there isn't confuion between my controller (createAction), my form action (createPost) and my route on index.php which is:
$router->add('createPost', ['controller' => 'Posts', 'action' => 'create']);

Thanx again

**Comment by daveh** [comment]
The `add` method in your model isn't returning anything, so by default this will return null. After the post is created successfully, you need to return true so that the controller code can redirect.

**Comment by matats** [comment]
Thank you sir. I got it working. Had to play around with return, as you said. It's so much fun learning. I goning to take another course on php
