### ISSUE TITLE
Integration with Dompdf

### ISSUE THREAD

**Issue by feramos60** [daveh/php-mvc#109]
Hi Dave

I have tried to integrate Dompdf with your MVC architecture, but the images in the PDF do not appear, I have tried to do the following by creating a method:

     /**
     * print pdf
     *
     */
    public function pdf()
    {
          
            // Set the Dompdf options
            
            $options = new Options;
            $options->setChroot(__DIR__);
            $options->setIsRemoteEnabled(true);

            $dompdf = new Dompdf($options);

            $html = View::getTemplate('Roles/hoja.html'); //path to the folder found in views           
            
            $dompdf->loadHtml($html);

            // (Optional) Setup the paper size and orientation
            $dompdf->setPaper('folio', 'portrait');

            // Render the HTML as PDF
            $dompdf->render();

            $dompdf->addInfo("Title", "Document"); // "add_info" in earlier versions of Dompdf

            $dompdf->stream('document.pdf');
        
    }

in the HTML of the view there is an image but I can't make it appear in the PDF, it seems that the path (\__DIR__) of the image does not correspond, I have tried in a thousand ways but it was impossible. For example I have changed (\__DIR__) for the path of the views but nothing.

I appreciate if you can give me a light to achieve it.

Thanks.

**Comment by daveh** [comment]
It could be a relative path or a permissions problem - try hardcoding the full path to the image (i.e. not a relative one) into the HTML; If that doesn't work, try moving the image to another location to see if that affects it

**Comment by feramos60** [comment]
Hello

I already put the absolute path, even putting localhost, but the image does not appear.

**Comment by daveh** [comment]
Try it with another image from the web in general, e.g. something like [this](https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png). That will tell us if it's a local image problem or a problem with the HTML layout.

**Comment by feramos60** [comment]
Hello

When I put that path I get the following:

Mensaje: 'tempnam(): file created in the system's temporary directory'

**Comment by daveh** [comment]
Ok, but does it work? Does it include the image? I believe the library makes a local copy of any remote images when it generates the PDF, which is what that message is referring to.

**Comment by feramos60** [comment]
no, it didn't work

**Comment by daveh** [comment]
So I can try and reproduce this locally, please can you give me details of your code - is the above method a controller action method? Also please can you send me the view and the path of the folder where the image is? Then I can try it here to see if I can work out why it isn't working.

**Comment by feramos60** [comment]
Hello
I solved it using the Mpdf library and using the relative path.
Thank you.
