### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by pkmahapatra** [daveh/php-mvc#11]
Even though I added 

`$router->add('home/details');`

some how the routing is not happening.
Controller is Home
Action is detailsAction

**Comment by daveh** [comment]
Hi,

in what way isn't it happening? Please can you describe exactly what happens? For example, do you get an error message? Please also include the URL that you're trying.

Thanks,
Dave

**Comment by BassemN** [comment]
@daveh I think you need to add `$router->add('{controller}/{action}');` [here](https://github.com/daveh/php-mvc/blob/master/public/index.php#L29) by default to prevent such issues.

**Comment by daveh** [comment]
That's a great idea @gonzela2006, done! :+1:

**Comment by BassemN** [comment]
Thank you :+1:
