### ISSUE TITLE
Route Problem

### ISSUE THREAD

**Issue by robertaonnis** [daveh/php-mvc#110]
Hi,
i'm trying to inser image in a view index.php file.
But the system return me 404 error.

I have create a folder in the route file like this images/nameofimage.png.

do you have an idea how can i solve this?

**Comment by daveh** [comment]
Public images would go in the public folder (and in a subfolder of that folder if you want). For example an image example.png in the public folder would be available at http://example.com/example.png

**Comment by robertaonnis** [comment]
Yes I have read all the code yesterday and I have discover. Thanks a Lot for your job.
