### ISSUE TITLE
Undefined index: email

### ISSUE THREAD

**Issue by ghost** [daveh/php-mvc#12]
Hello,

I really like your MVC template and I'm actually using it.
So I want to know how i can add params to an URL, because I tried everything but it's not working.

Actually in my index.php I have write down this code:

`$router->add('contact', ['controller' => 'Home', 'action' => 'contact', 'params': '{email:},{name:}']);`
and in the HomeController I have this code:
`public function contact($email,$name)
    {
        $email = $this->route_params['email'];
        $name = $this->route_params['name'];
        echo $email. ' ' .$name;
    }`

Maybe you can give a code example ?

Thank you very much (beginning with PHP) 
Abdellah

**Comment by daveh** [comment]
Hi Abdellah,

thank you for your interest in my framework!

What exactly are you trying to do, have a URL like this:

example.com/contact/name@example.com/name ?

Parameters in a URL go in the first argument of the route, like this:

`$router->add('contact/{email}/{name}', ['controller' => 'Home', 'action' => 'contact'']);`

Then in the controller action, you can get the values of these parameters from a URL using the `route_params` array:

```
public function contactAction()
{
    $email = $this->route_params['email'];
    $name = $this->route_params['name'];
    // ...
}
```

Having said that, if you're creating a contact form, you wouldn't have the form data passed in the URL like that, as it's would be saved in the browser's history (so anyone could see it).

Instead, you'd have a route like this for example:

`$router->add('contact', ['controller' => 'Home', 'action' => 'contact'']);`

Then a controller action where you got the results of the form from the [$_POST](http://php.net/manual/en/reserved.variables.post.php) array:

```
public function contactAction()
{
    $email = $_POST['email'];
    $name = $_POST['name'];
    // ...
}
```

(Using an MVC framework is a bit different to "regular" PHP if you're not used to it!)

Does that help?

Cheers,
Dave

**Comment by ghost** [comment]
Hello, 

Thank you for your fast answer. 
Yes I finally used the second way (with the $_POST)

Now that I have an example with the first code, I understand how it works.
It's just that I'm a .NET from years and I don't know very well working with PHP.

By the the way your MVC Framework is really awesome ! ;) 

Kind regards,
Abdellah

**Comment by daveh** [comment]
Hi Abdellah,

great, glad you got it working!

Thank you for your kind comments! :-)

Best wishes,
Dave
