### ISSUE TITLE
$_SERVER QUERY_STRING Empty, nginx ddev Config Note

### ISSUE THREAD

**Issue by aXb0t** [daveh/php-mvc#121]
This is not a bug report.  More of additional documentation by GitHub Issue.

Just posting this in case somebody else comes here from the Udemy course, having set up a default ddev installation (or otherwise running nginx) and having issues with the router parsing URLs

I spent a good minute debugging why `$router->add('{controller}/{action}');` was not resolving to controllers, and finally inspected Superglobals > $_SERVER['QUERY_STRING'] and found it empty.

That led me to read the documentation more carefully and I found the nginx config note and file: https://raw.githubusercontent.com/daveh/php-mvc/master/nginx-configuration.txt

I skipped the prerequisite setup of php-mvc course, so maybe missed some instructions, there, too.

I just reset ddev to run `apache-fpm` and now php-mvc works like a charm for me.

**Comment by daveh** [comment]
Thank you for sharing @alexb7217 ! I'll make sure these instructions are included in the course when I update it.

**Comment by aXb0t** [comment]
I see now some other Issues that have been closed related to this. Do you want me to close this one, too?

**Comment by daveh** [comment]
@alexb7217 Ok yes, thank you!

**Comment by aXb0t** [comment]
Will do. The nginx configuration file example works fine when appended to .ddev -> nginx_full -> nginx-site.conf to handle question mark queries in the URL
