### ISSUE TITLE
Return value must be of type App\Controllers\Response, Framework\Response 

### ISSUE THREAD

**Issue by tenk-rgb** [daveh/php-mvc#127]
hello

i'm tryng to start the project but i'm getting this error before or after putting the database info in .env

i'm using php latest is that it?

![image](https://github.com/daveh/php-mvc/assets/80407911/d9eab1cf-0d90-4eef-939b-6574a44bd8be)

**Comment by ghost** [comment]
add this in file src/App/Controllers/Home.php
use Framework\Response;

**Comment by daveh** [comment]
@vedastudio Thanks for this, I just updated the repo to include it.

**Comment by tenk-rgb** [comment]
> add this in file src/App/Controllers/Home.php use Framework\Response;

it works, thanks!
