### ISSUE TITLE
Routing groups

### ISSUE THREAD

**Issue by K1Yuhh** [daveh/php-mvc#128]
Hey, 

I enjoyed your course on Udemy its one of the best at the moment.

You've said in 2020 that you will add route groups. 

Link: https://github.com/daveh/php-mvc/issues/68

When are you releasing it since I'm interested in some advanced topics about MVC.

**Comment by daveh** [comment]
It is on my list, but I'm afraid I can't say when it'll be available, I have a lot on right now - I'll try and do it as soon as I can.

**Comment by K1Yuhh** [comment]
Please do so. The way you explain makes me wanna watch every episode. I learnt alot from you. 

Take care!
