### ISSUE TITLE
.htaccess file not wotking in wamp

### ISSUE THREAD

**Issue by mexantos** [daveh/php-mvc#14]
i watched your video somewhere else and i follow step by step, but seem .htaccess was a burden in wamp that always return 500 or 400 error.
in the end ill' finished your video without htaccess. so to access posts route i use http://localhost?posts/index. this is do the trick for me following your video. i want to know why this happen in wamp(php 7x).
another way to improve this mvc, that i want slashing in the end of route not trigger error, may be you can do with htaccess or with some kind tweak on your Route.php file so if someone access with trailing slash, it should be remove in the end of uri.
one more thing this mvc can improve if {controller}{indexAction} automatically redirect to just controller i mean like this http://localhost/posts/index redirect to http://localhost/posts

**Comment by BassemN** [comment]
To fix the wamp issue edit your `.htaccess` file and remove the following line
```
RewriteBase /
```

**Comment by daveh** [comment]
Hi,

thank you for letting me know about the WAMP issue. I left the `RewriteBase /` line in so it was compatible with .htaccess files when the public folder hasn't been assigned as the root. I'll look into a fix so it works universally.

Also, thank you for the suggestion of the default action, good idea! I'll look into the necessary code modifications and let you know.

Cheers,
Dave

**Comment by BassemN** [comment]
Hi @daveh,

I think you should comment this line by default and add a comment like the this https://github.com/joomla/joomla-cms/blob/staging/htaccess.txt#L58-L64

Thanks

**Comment by daveh** [comment]
Hi,

that's a great idea, thank you for the idea and example! I've tested it and I'm happy with that, so I've done as you suggested.

Cheers,
Dave

**Comment by BassemN** [comment]
@daveh Thank you
