### ISSUE TITLE
Home page is not displaying

### ISSUE THREAD

**Issue by Beloxs** [daveh/php-mvc#15]
Hello Daveh,
I am trying your framework, but the home page is not diplaying.
I am using Linux ubuntu. I also use the bultin php server with the command php -S localhost:5000 when I am in the public folder of the framework.
my url is : http://localhost:5000/
I have this error:
Uncaught exception: 'ErrorException'

Message: 'Undefined index: QUERY_STRING'

Stack trace:

#0 /home/myuser/PHPProjects/php-mvc/public/index.php(32): Core\Error::errorHandler(8, 'Undefined index...', '/home/myuser/PH...', 32, Array)
#1 {main}
Thrown in '/home/myuser/PHPProjects/php-mvc/public/index.php' on line 32
May be I am missing something . Could you help me ?

**Comment by BassemN** [comment]
Hi,
@daveh has updated this file https://github.com/daveh/php-mvc/blob/master/public/.htaccess with a new code, please try to use it and feed me back.

**Comment by Beloxs** [comment]
Hi @gonzela2006 ! I am using this new file, but it is not still working. I have a Fatal error with the message I mentioned above in my browser.
Here are my logs:
PHP 7.0.22-0ubuntu0.16.04.1 Development Server started at Mon Oct 30 09:07:07 2017
Listening on http://localhost:5000
Document root is /home/myuser/PHPProjects/php-mvc/public
Press Ctrl-C to quit.
[Mon Oct 30 09:07:16 2017] 127.0.0.1:54732 [500]: /
[Mon Oct 30 09:07:16 2017] 127.0.0.1:54736 [404]: /favicon.ico - No such file or directory

**Comment by BassemN** [comment]
I advise you not to use the PHP built-in server as It is not intended to be a full-featured web server as per [PHP manual](https://secure.php.net/manual/en/features.commandline.webserver.php). For Ubuntu, try to use XAMPP or AMPPS.

**Comment by daveh** [comment]
Hi,

that's right, the framework won't work with the PHP built-in web server. I recommend XAMPP for all platforms.

Cheers,
Dave

**Comment by Beloxs** [comment]
Ok, I will try XAMP and feed back you !  Thank you !

**Comment by Beloxs** [comment]
I am back, everything is ok now. Welcome page is displaying with both LAMP and XAMP. We keep in touch. Thank you a lot for your help @gonzela2006  and @daveh
