### ISSUE TITLE
Controller capabilities

### ISSUE THREAD

**Issue by nuriyevn** [daveh/php-mvc#16]
Hello Dave,

What if we need to pass member variable from one controller method to another controller method?  
Is it possible without using global $_SESSION ?
for that purpose, do I need to use static members or it is possible to instantiate controller class somewhere in router?
Thanks in advance.

**Comment by daveh** [comment]
Hi,

I'm not sure what you mean, do you mean from one request to another? If so, and you don't want to use the session, you could do it in the query string for example.

Please can you clarify by giving me an example of exactly what you want to do?

Thanks,
Dave

**Comment by nuriyevn** [comment]
Hi,

I will divide question into two small sub-questions
Let's assume we have following code:

```
...
class SessionController extends \Core\Controller { ... }
...

```
```
class Profile extends \Core\SessionController
{
    public $uploadedFiles = [];
    
    public function generateRandomString($length = 10) {
        ... some random string generation ...
        return $randomString;
    }
    public function addFile()
    {
        $this->showFiles();
        array_push($this->uploadedFiles, $this->generateRandomString());
        $this->showFiles();
    }
    public function showFiles()
    {
        var_dump(implode(",", $this->uploadedFiles));
    }
}

```

The problem that output is following
string(0) "" string(10) "4VusBCaAiC"


It has always one element in array, because first call $this->showFiles()  inside addFile()  always empty.
Probably, there is  variable scope problem so that $uploadedFiles  is being initialized at each addFile call.

I understand that my PHP  skills is not yet enough and there is different scope rules that in my C++, 
so what is the "good" way to make member "work" so that  $uploadedFiles accumulates all strings (filenames).
Maybe instantiation of Controller or using static members?

That was first sub-question.

The second sub-question related to scope.
Why we use static in Model classes? Is it ok to use static members in Model classes to interchange data between Model methods? or actually, because, it's model and we do not want to couple methods at all, rather leaving them as wrapper methods for SQL queries and leaving all logic behind, in controller?

My question most probably arose from lack of my PHP experience.

BTW,  Thank you for your course.

**Comment by daveh** [comment]
> BTW, Thank you for your course.

Do you mind asking your questions inside the course on Udemy? That way other students can see (and contribute to) the answer. You can ask it in the "questions" section when you access the course.

When you do, please can you give me a bit more information about your problem? For example, please can you include the controller action where you're calling the `showFiles` method?

Thanks,
Dave

**Comment by nuriyevn** [comment]
Okay, I'll ask there.
