### ISSUE TITLE
rest-api

### ISSUE THREAD

**Issue by lexxeech** [daveh/php-mvc#17]
Hello, I gonna use your template for my university homework. 

Can you explain me how I can:
1. Add POST routes
2. Add Router which returns some json?

I try like, but have nothing got 
    public function testAction()
    {
      return [
        'status' => 'OK',
        'items' => [],
      ];
    }

**Comment by daveh** [comment]
Hi,

the framework doesn't support routes based on the request method. To check if the POST method was used in an action, check the `REQUEST_METHOD` element of the `$_SERVER` array:

```
if ($_SERVER["REQUEST_METHOD"] == "POST") {

}
```

To output something from an action method, you need to echo it. So to output some JSON, you simply need to call the [json_encode](http://php.net/manual/en/function.json-encode.php) method on it, for example:

```
public function testAction()
{
    echo json_encode([
        'status' => 'OK',
        'items' => []
    ]);
}
```

Does that help?

**Comment by lexxeech** [comment]
Thank you , bruv , thank you ! Its really work
