### ISSUE TITLE
Css, js

### ISSUE THREAD

**Issue by Felda01** [daveh/php-mvc#18]
Hello,
Im using your template in school project,

Can you explain me how I can include css and js files ?

Thanks

**Comment by daveh** [comment]
Hi,

just put them in the public folder, then you can reference them as normal - for example, if you had a styles.css file in a css folder, and a script.js file in a js folder, you would reference them like this:

```
<link rel="stylesheet" type="text/css" href="/css/styles.css">

<script src="/js/script.js"></script>
```

The CSS link goes in the `<head>` section, and the JavaScript link can go there too or at the bottom of your `<body>` section, depending on how you're using the JavaScript.

Does that help?

Cheers,
Dave

**Comment by Felda01** [comment]
yes, thanks
i had them in other folder :)
