### ISSUE TITLE
Helper Class

### ISSUE THREAD

**Issue by ghost** [daveh/php-mvc#19]
hi,
I need to pass some DB data to every page (for navbar)

how can I do this??

**Comment by daveh** [comment]
You can use a [Twig global variable](https://twig.symfony.com/doc/2.x/advanced.html#globals), for example:

```
$twig = new Twig_Environment($loader);
$twig->addGlobal('navbar_data', $data);
```

**Comment by ghost** [comment]
thanks!
but Where should I add?

**Comment by daveh** [comment]
You need to add that where you create the Twig_Environment object, so in this case in the Core/View class. For example, if you want to have the PHP `$_SESSION` array available inside Twig templates:

`$twig->addGlobal('session', $_SESSION);`

**Comment by ghost** [comment]
it's ok to connect to the database in View ??

**Comment by ghost** [comment]
and if I need some extra functions in the controllers should I add them in Core\Controller?

**Comment by daveh** [comment]
Whereas you _could_ connect to the database in a view, that totally goes against the idea of separating application code and presentation code in an MVC framework. Normally the view and the model (where you connect to the database) are totally separate. This is covered in detail on [the course](http://daveh.io/r/ghmvc).

Yes, if you need some extra methods in all controllers, you add them to the Core/Controller class, as all the controllers should extend this class.
