### ISSUE TITLE
Fatal error - No such file or directory

### ISSUE THREAD

**Issue by ianonthenet** [daveh/php-mvc#2]
Hi,
Interesting project, but it doesn't work for me.
I followed the installation instructions (composer ok, web root in "public") and when I try to see homepage, I get the error below.
Any idea ? I missed something ?

> Fatal error
> Uncaught exception: 'ErrorException'
> Message: 'file_get_contents(App/Views/Home/index.html): failed to open stream: No such file or directory'
> 
> Stack trace:
> # 0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', 'K:\Create\ftp_l...', 131, Array)
> # 1 K:\test\php-mvc-master\vendor\twig\twig\lib\Twig\Loader\Filesystem.php(131): file_get_contents('App/Views/Home/...')
> # 2 K:\test\php-mvc-master\vendor\twig\twig\lib\Twig\Environment.php(406): Twig_Loader_Filesystem->getSource('Home/index.html')
> # 3 K:\test\php-mvc-master\vendor\twig\twig\lib\Twig\Environment.php(357): Twig_Environment->loadTemplate('Home/index.html')
> # 4 K:\test\php-mvc-master\Core\View.php(51): Twig_Environment->render('Home/index.html', Array)
> # 5 K:\test\php-mvc-master\App\Controllers\Home.php(22): Core\View::renderTemplate('Home/index.html')
> # 6 [internal function]: App\Controllers\Home->indexAction()
> # 7 K:\test\php-mvc-master\Core\Controller.php(48): call_user_func_array(Array, Array)
> # 8 K:\test\php-mvc-master\Core\Router.php(121): Core\Controller->__call('index', Array)
> # 9 K:\test\php-mvc-master\Core\Router.php(121): App\Controllers\Home->index()
> # 10 K:\test\php-mvc-master\public\index.php(37): Core\Router->dispatch('')
> # 11 {main}
> 
> Thrown in 'K:\test\php-mvc-master\vendor\twig\twig\lib\Twig\Loader\Filesystem.php' on line 131

**Comment by daveh** [comment]
Hi,

the latest version of Twig introduced an incompatibility with the line in the Core/View.php class that loads the template file. I've just committed the following fix - line 47 in Core/View.php has been changed from

`$loader = new \Twig_Loader_Filesystem('../App/Views');`

to

`$loader = new \Twig_Loader_Filesystem(dirname(__DIR__) . '/App/Views');`

You can make the change yourself or pull the latest version of the code. That should fix it (it has for me anyway) - please let me know if it doesn't!

Thanks for letting me know :-)

Cheers,
Dave

**Comment by ianonthenet** [comment]
It works ! Thanks a lot ^^
