### ISSUE TITLE
Includes in Views

### ISSUE THREAD

**Issue by Khashul** [daveh/php-mvc#20]
Hi,

Great course, really enjoyed it.

I'm having difficulty finding a way to include a view within a view. I have created a News Class which pulls the latest news posts from the DB but I'd like the displayed news posts visible on a few different Views so wanted to include a View within a View.

This may not be the best way of doing it but would normally use an include so feedback would be greatly appreciated.

Thanks,

**Comment by daveh** [comment]
Hi,

happy to help, but as this question is related to the course, please can you ask the question inside the course on Udemy? That way, other students can benefit from the answers, and even contribute to them.

You can ask a new question in the Q&A section of the course. I'll look out for your question there!

Thanks,
Dave
