### ISSUE TITLE
Unstable Routing

### ISSUE THREAD

**Issue by cagcak** [daveh/php-mvc#21]
Hi. 
I added about.html inside Views/Home/ and in Home controller added a aboutAction() method which does render twig view file (about.html) then finally register for routing in index.php:

`$router->add('about', ['controller' => 'Home', 'action' => 'about']);`

and yet I receive error:

```
Fatal error
Uncaught exception: 'Exception'

Message: 'No route matched.'

Stack trace:

#0 /home/php-mvc/public/index.php(35): Core\Router->dispatch('about')
#1 {main}
Thrown in '/home/php-mvc/Core/Router.php' on line 130
```

Anyway I tried to change error handlers code inside echo just to see what loads, but no changes shows up, too. 

I changed the config line like below but still getting the same errors:

`const SHOW_ERRORS = false;`

This is strange. I cant figure it out. I thought that It may be rendered twig files but I cleared all caches and did autoload dump composer thing. No luck.

**Comment by cagcak** [comment]
sorry for this trash issue, I figured that I didn't uncomment the .htaccess rewrite base rule. it works now.

**Comment by Algoclogic** [comment]
How can I add  other routes .

**Comment by cagcak** [comment]
#22

**Comment by daveh** [comment]
Please see [my response](https://github.com/daveh/php-mvc/issues/22#issuecomment-373203889) to the other issue.
