### ISSUE TITLE
Passing variables from Controller to View

### ISSUE THREAD

**Issue by cagcak** [daveh/php-mvc#23]
Not really sure is there any complication in passing variables from controller methods to views

```
    public function indexAction()
    {
        $data = [
               'title' => 'some value'
        ];
        View::render('Home/index.php', $data);
    }
```

view file:

` <h1><?php echo $data['title']; ?></h1>`

returns nothing rendered. In fact, it does work like in CodeIgniter:

`<h1><?php echo $title; ?></h1>`

**Comment by daveh** [comment]
As you closed this issue, are you still having a problem? Please let me know.

**Comment by cagcak** [comment]
Hi @daveh . I don't have a problem in this issue anymore, it works now. I just didn't figure out why I have to specify calling a passed data with its name and key in some frameworks, but not in this and CodeIgniter. And why whole view returnd or nothing renders if a calling passed data is not set or found ? Thanks in advance.

**Comment by daveh** [comment]
If the data isn't found and nothing renders, it could be because an error is occurring but not being displayed, which results in a blank page. You can turn errors on with the following code for example:

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
