### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by telemoes** [daveh/php-mvc#25]
Hi,

i have a question, how kan i make a routing like this
seo url: abc-def-eeee-eeee this must goto the pagecontroller action front
I did this: 
$router->add('[^a-zA-Z0-9\-]+/', ['controller' => 'pages', 'action' => 'front']);

Also i have this kind of routings:
$router->add('chalets/prices', ['controller' => 'chalets', 'action' => 'showAllPrices']);
$router->add('chalets/prices-[^a-zA-Z\-]+/', ['controller' => 'chalets', 'action' => 'showChaletPrices']);
Seo url: chalets/prices of chalets/prices-all or chaletname
Evertything goes to  chalets/prices i todd it is gona to chalets/showAllPrices thats is wat 1 want.

For blog i did this
$router->add('blog/[^a-zA-Z0-9\-]+/', ['controller' => 'blog', 'action' => 'front']);
Working perfect!

I hope you can help me with the chalets routing issue
Thx

**Comment by cagcak** [comment]
Define generic routes before registering actuals

```
$router->add('{controller}/{action}');
$router->add('chalets/{[^a-zA-Z0-9-]+/}/{action}', , ['namespace' => '<NAMESPACE_OF_your_chalets_controller']);
```
#22 
Duplicate of #22

**Comment by telemoes** [comment]
Hi cagcak,

Thanks for your reaction ;)

i'am not sure it is the same like #22 because in the action method i have mij routings vars.
I do this...
$router->add('chalets/price-{[^a-zA-Z0-9-]+/}/', ['action' => 'showChaletPrices',]);
The seo url is "chalets/price-the-name-of-the-chalet" then the action must be showChaletPrices
So i do not need the namespace because the controller is right, only i want a other action

The scripts wants to: ChaletsController->priceChaletAlmblick() OR  ChaletsController->priceChaletBelleNovaFrance()
How do i get the script to: ChaletsController->showChaletPrices

thx anyway

**Comment by cagcak** [comment]
I think you are trying to make any route matches in child urls. But in 
https://github.com/daveh/php-mvc/blob/dc047dfa7a5b99ceadcc18c4b3f31e5e1a45cd37/Core/Router.php#L33
routes are converted from string to regex. 
It might need major changes in core router. Instead you may want to use add manually by automated for:
`$router->add('parent-url/child-url/{controller}/{action}/{id:\d+}');`
like below: 

```
function addRouteToEnd($route, $controller, $action)
{
  $router = public/index.php
  $lines = file($router);
  $counter = 0;
  while ($counter < 2) {
    array_pop($lines); # removes the last element from an array
    $counter++;
  }
  $deleteDispatch = implode('', $lines);
  $addRoute = "";
  $addRoute .= "\$router->add('" . $route . "', ['controller' => '". $controller ."', 'action' => '".$action."']);\n";
  $addRoute .= "\n\$router->dispatch(\$_SERVER['QUERY_STRING']);";
  file_put_contents($router, array($deleteDispatch, $addRoute), LOCK_EX);
}
```

This method simply adds routes as lines into `index.php` you may use in your controller as a helper function:
`addRouteToEnd('parent-url/child-url', 'ChildControllerFolder' .'\\'. ChildController, 'showSomething');`
then after calling, it will appear in routing table as 
`$router->add('parent-url/child-url', ['controller' => 'ChildControllerFolder\ChildController', 'action' => 'showSomething']);`

I hope it helps something.

**Comment by telemoes** [comment]
Hi,

Ehu thats is not what i mean i guess.

My seo url is: www.domain.com/chalets/price-chalet-bellanova-france
The router goes to: ChaletsController->priceChaletBelleNovaFrance() (controller->action)
I want that the router goes to : ChaletsController->showChaletPrices (so i can make one method for all chalets)

It's the action thats not does what i want the controller is good only the action is not good.

thats al

**Comment by cagcak** [comment]
I assume you didnt forget to add 'Action' suffix at the end

**Comment by telemoes** [comment]
cagcak what you mean?

**Comment by cagcak** [comment]
> Controller classes contain methods that are the actions. To create an action, add the Action suffix to the method name. The sample controller in App/Controllers/Home.php has a sample index action.

**Comment by telemoes** [comment]
When i do call the method in the controller Chalets to showChaletPricesAction it's still not working.
I think it is not posseble with this router and i must changed in the core.

**Comment by cagcak** [comment]
please infrom me if that regex route work

**Comment by telemoes** [comment]
I add http://altorouter.com/ to this framework and work perfect

**Comment by daveh** [comment]
Hi @telemoes,

you need to specify the name of the variable in the route, before the regular expression. So for example this route:

`$router->add('chalets/{chalet:[a-z0-9-]+}', ['controller' => 'Chalets', 'action' => 'showChaletPrices']);`

will make URLs like this:

example.com/chalets/price-chalet-bellanova-france

run the `showChaletPricesAction` method in the Chalets controller. You can get the value of the variable from the URL in the action method using the `route_params` array:

```
class Chalets extends \Core\Controller
{
    public function showChaletPricesAction()
    {
        $chalet = $this->route_params['chalet'];
        ...
    }
}
```

**Comment by qwersk** [comment]
Hello. I have a question about routing too. Can you help me?
I have a file filled with urls, controllers and actions (like [this](https://github.com/victor-zinchenko/shop.php-start.com/blob/master/config/routes.php) ), so can I loop through this file to add routes with $router->add() function?
May be like this:
`require routes.php`
`...`
`for ($i = 0; $i < count($routes); $i++) {`
`    $router->add($url, ['controller' => $controller, 'action' => $action]);`
`}`
Thanks in advance and sorry for my English:)

**Comment by daveh** [comment]
Hi @qwersk,

yes, that would work, as long as you created the router object first, before you required the routes.php file. You could also use a `foreach` loop instead of a simple `for` loop:

```
foreach ($routes as $route => $result) {
   $router->add($url, ['controller' => $controller, 'action' => $action]);
}
```
Cheers,
Dave

**Comment by neto737** [comment]
@telemoes how you replaced the original router by AltoRouter? Can you explain or share your code with us?

**Comment by telemoes** [comment]
Sorry boys for the very late reaction.
It's not so difficult change.
First i download altorouter and put it in the core directory.

In my index.php i call the router with
```
$router = new Core\AltoRouter();
$router->setBasePath('/public_html');
// map homepage
$router->map( 'GET', '/', 'home#front');

// Admin routers
$router->addRoutes([]) // my routes
$router->dispatch();
```
And a big array with routes (take a look at altorouter how)
I make one change in the Altoroute code to make it work with this framework
i put this on line 240

```
                list( $controller, $action ) = explode( '#', $target );
                $this->params['controller'] = $controller;
                $this->params['action'] = $action;
                $this->params['method'] = $methods;
                if (count($params)) {
                    foreach ($params as $key => $param) {
                        $this->params[$key] = $param;
                    }
                }
```
And it was working for me.

@daveh i want to share some code with you i make some very nice changes to the base controller and model

**Comment by daveh** [comment]
@telemoes ok great, please do!

**Comment by rezadavari** [comment]
Hi
I want to route  to a controller's action with some parameters like Laravel:
Route::get('myRequest/{par1}/{par2}/{par3}', 'SomeController@SomeAction'); 

and in Controller:
public function SomeAction($par1,$par2,$par3,) 
{
     $id = $par1;
     $gsID = $par2;
     .... and so on for all your variables.
 }
 l wrote a route like this:
$router->add('{controller}/{action}/{name:[a-z]+}');
 and in Home controller  the action is:

public function HelloName($name){

        $temp=["name"=>$name];
        View::renderTemplate('Home/index2.html',$temp);
    }

when I get the route I get this error:

Uncaught exception: 'ArgumentCountError'

Message: 'Too few arguments to function App\Controllers\Home::HelloName(), 0 passed in ......\Core\Router.php on line 137 and exactly 1 expected'

could you help me where is wrong/

**Comment by daveh** [comment]
Hi,

the router doesn't work like that in this framework (at least not yet - I'm working on an update). If you add a route like this:

`$router->add('{controller}/{action}/{id:\d+}');`

the `controller` and `action` variables will be used to run the action method, and the `id` variable will be available in that action method in the route_params array, e.g.

`$id = $this->route_params['id'];`

Action methods don't take any arguments, all route parameters are passed like that.

**Comment by telemoes** [comment]
I change the core model a little bit ;)

`namespace App\Core;

use PDO;
use App\Models\Sys_log;

abstract class Model
{
    /**
     * primaryKey you can overrule this in de model class when you have a other primary key in your DB.
     * @var string
     */
    protected static $primaryKey = "id";
    private   static $db = null;
    public    static $queries = [];

    public function __get($name)
    {
        return $this->$name;
    }

    public function __set($name, $value)
    {
        $this->$name = $value;
    }
    
    public function __isset($name)
    {
        return array_key_exists($name, $this);
    }

    /**
     * Get object from $id
     *
     * @param int $id
     * @param boolean $format (false returns object)
     * @return mixed
     */
    public static function find($id, $format=false)
    {
        // Make model
        $modelName = get_called_class();

        // Get data
        $q = "SELECT * FROM `" . static::TABLE . "` WHERE `" . static::$primaryKey . "` = :id"
            . (static::DELETED === true ? " AND deleted_at IS NULL" : null);
        $stmt = self::$db->prepare($q);
        $stmt->bindParam('id', $id, PDO::PARAM_INT);
        $stmt->execute();
        $object = $stmt->fetchObject($modelName);
        return ($format === false ? $object : (array)$object);
    }

    /**
     * @param string $q
     * @param array $cols
     * @param bool $all
     * @return bool or Object or array
     */
    public static function select($q, $cols=[], $all=false)
    {
        self::getDB();
        try {
            $handler = self::$db->prepare($q);
            if ($cols) {
                foreach ($cols as $col => &$val) {
                    if ($col != 'primaryKey') {
                        if (is_int($val)) {
                            $handler->bindParam($col, $val, PDO::PARAM_INT);
                        } elseif (is_null($val)) {
                            $handler->bindParam($col, $val, PDO::PARAM_NULL);
                        } elseif (is_bool($val)) {
                            $handler->bindParam($col, $val, PDO::PARAM_BOOL);
                        } else {
                            $handler->bindParam($col, $val, PDO::PARAM_STR);
                        }
                    }
                }
            }
            $handler->execute();
            if ($all !== false) {
                $items = $handler->fetchAll(PDO::FETCH_ASSOC);
            } else {
                $modelName = get_called_class();
                $items = $handler->fetchObject($modelName);
            }
            self::$queries[] = [
                'query' => $q,
                'vars'  => (is_array($cols) ? implode(", ", $cols) : null),
                'time'  => date('d-m-Y H:i:s'),
            ];
        } catch (PDOException $e)
        {

        }

        return ($items ? $items : false);
    }

    /**
     * Delete record from DB.
     * @param string $cols
     * @return mixed
     */
    public static function delete($cols)
    {
        self::getDB();
        $first = true;
        $q = "DELETE FROM `" . static::TABLE . "` WHERE ";
        foreach ($cols as $col => $val) {
            $q .= ($first !== true ? " AND " : null);
            $q .= '`' . $col . '` = :' . $col;
            if ($first === true)
                $first = false;
        }
        $handler = self::$db->prepare($q);
        foreach ($cols as $col => &$val) {
            if (is_int($val)) {
                $handler->bindParam($col, $val, PDO::PARAM_INT);
            } elseif (is_null($val)) {
                $handler->bindParam($col, $val, PDO::PARAM_NULL);
            } elseif (is_bool($val)) {
                $handler->bindParam($col, $val, PDO::PARAM_BOOL);
            } else {
                $handler->bindParam($col, $val, PDO::PARAM_STR);
            }
        }
        $handler->execute();
        return $handler->rowCount();
    }

    /**
     * Save object to the database
     * @param bool $log
     * @param bool $returnObject
     * @return bool
     */
    public function save($log=true, $returnObject=true)
    {
        $now = date('Y-m-d H:i:s');
        $insert = false;
        if (!array_key_exists(static::$primaryKey, $this)) {
            $insert = true;
        }

        /**
         * when $insert = true then insert record
         * when $insert = false then update record
         */
        $q = null;
        if ($insert !== false) {
            $q = $this->insert();
            if (static::TIMESTAMPS === true) {
                $this->created_at = $now;
                $this->updated_at = $now;
            }
            if (static::USER === true && !empty(\Login::getUserId())) {
                $this->created_by = \Login::getUserId();
                $this->updated_by = \Login::getUserId();
            }
        } else {
            $q = $this->update();
            if (static::TIMESTAMPS === true) {
                $this->updated_at = $now;
            }
            if (static::USER === true && !empty(\Login::getUserId())) {
                $this->updated_by = \Login::getUserId();
            }
        }

        /**
         *  Run query
         */
        $id = null;
        try {
            $handler = self::$db->prepare($q);
            foreach ($this as $col => &$val) {
                if ($col != 'primaryKey') {
                    if (is_int($val)) {
                        $handler->bindParam($col, $val, PDO::PARAM_INT);
                    } elseif (is_null($val)) {
                        $handler->bindParam($col, $val, PDO::PARAM_NULL);
                    } elseif (is_bool($val)) {
                        $handler->bindParam($col, $val, PDO::PARAM_BOOL);
                    } else {
                        $handler->bindParam($col, $val, PDO::PARAM_STR);
                    }
                }
            }
            $handler->execute();
            $key = static::$primaryKey;
            if ($insert === true) {
                $this->$key = self::$db->lastInsertId();
            }
            $handler = null;
            self::$queries[] = [
                'query' => $q,
                'time'  => $now,
            ];
            //  Log action
            if ($log === true && !empty(\Login::getUserId())) {
                Sys_log::logAction($this->$key, get_called_class(), ($insert !== false ? 'create' : 'edit'));
            }

            //  Return object
            if ($returnObject === true) {
                return self::find($this->$key);
            } else {
                return true;
            }
        } catch (PDOException $e)
        {

        }
        return false;
    }

    /**
     * @param array $result
     * @param string $sortByCol
     * @return array
     */
    public static function keyBy($result, $sortByCol)
    {
        if (empty($result)) {
            return false;
        }
        $array = [];
        foreach ($result as $key => $values)
        {
            if (array_key_exists($sortByCol, $values)) {
                $array[$values[$sortByCol]] = $values;
            }
        }
        return (count($array) ? $array : false);
    }

    /**
     * create insert query from object
     * 
     * @return string
     */
    private function insert()
    {
        $values = $cols = null;
        $q = "INSERT INTO " . static::TABLE;
        foreach ($this as $col => $val) {
            if ($col != 'primaryKey') {
                $cols .= (strlen($cols) ? ", " : null) . "`" . $col . "`";
                $values .= (strlen($values) ? ", " : null) . ":" . $col;
            }
        }
        if (static::TIMESTAMPS === true) {
            $cols   .= ", `created_at`, `updated_at`";
            $values .= ", :created_at, :updated_at";
        }
        if (static::USER === true && !empty(\Login::getUserId())) {
            $cols   .= ", `created_by`, `updated_by`";
            $values .= ", :created_by, :updated_by";
        }
        $q .= "(" . $cols . ") VALUES (" . $values . ")";
        return $q;
    }

    /**
     * create update query from object
     * 
     * @return string
     */
    private function update()
    {
        $first = true;
        $q = "UPDATE `" . static::TABLE . "` SET ";
        foreach ($this as $col => $val) {
            if (!in_array($col, ['primaryKey', 'id'])) {
                $q .= ($first !== true ? ", " : null);
                $q .= '`' . $col . '` = :' . $col;
                if ($first === true)
                    $first = false;
            }
        }
        
        $q .= " WHERE `" . static::$primaryKey . "` = :" . static::$primaryKey;
        return $q;
    }

    /**
     * Get the PDO database connection
     *
     * @return mixed
     */
    protected static function getDB()
    {
        if (!empty(self::$db)) {
            return;
        }
    
        $dsn = 'mysql:host=' . getenv('DB_HOST') . ';dbname=' . getenv('DB_DATABASE') . ';charset=utf8';
        self::$db = new PDO($dsn, getenv('DB_USERNAME'), getenv('DB_PASSWORD'));
    
        // Throw an Exception when an error occurs
        self::$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
        return self::$db;
    }

}`

This how look the normal model
`
namespace App\Models;

use App\Core\Model;

class Menu extends Model
{
    private static $db = null;

    const TABLE         = "menu";
    const DELETED       = true;
    const TIMESTAMPS    = true;
    const USER          = true;
}
`

**Comment by daveh** [comment]
Cool, thank you for sharing @telemoes!

**Comment by telemoes** [comment]
i think there are something that can beter do you have comments?

**Comment by daveh** [comment]
A few things, yes - your `__isset` method is using `array_key_exists`, but if you want to see if a property exists on an object, (as opposed to a key in an array) you should use [property_exists](http://php.net/manual/en/function.property-exists.php) instead. 

You've also got a few hardcoded things in there, that might be better passed as parameters, and you're repeating that block where you bind values in more than one method - it might be better to extract that out into a separate method for example.

Other than that, it all seems fine - you've got some good ideas in there to reduce your model code.

Sorry I don't have time for a more in-depth review of your code, I'm working on a major update to the codebase at the moment, and I might add something like this to the code if I think it's a good fit.

Thanks for your continued interest!

**Comment by telemoes** [comment]
HI i make the changes you say and it's beter but i make some more nice features like function

- All to get all records
- Dropdown to gen selectboxes from a model
- updateOrCreate (update of Insert model to DB)
- fillOutObject fills the object with the given data i use it by update of create but you can also call it in your controller.

**Comment by daveh** [comment]
Ok - if you share your code, I'll have a look and make some comments if you like

**Comment by telemoes** [comment]
De Model:
`
namespace App\Core;

use PDO;
use App\Models\Sys_log;

abstract class Model
{
    /**
     * primaryKey you can overrule this in de model class when you have a other primary key in your DB.
     * @var string
     */
    protected static $primaryKey = "id";
    private   static $db = null;
    public    static $queries = [];

    public function __get($name)
    {
        return $this->$name;
    }

    public function __set($name, $value)
    {
        $this->$name = $value;
    }
    
    public function __isset($name)
    {
        return (property_exists($name, $this) ? true : false);
    }

    /**
     * Get object from $id
     *
     * @param int $id
     * @param boolean $format (false returns object)
     * @return mixed
     */
    public static function find($id, $format=false)
    {
        $q = "SELECT * FROM `" . static::TABLE . "` WHERE `" . static::$primaryKey . "` = :id"
            . (static::DELETED === true ? " AND deleted_at IS NULL" : null);
        $stmt = self::$db->prepare($q);
        $stmt->bindParam('id', $id, PDO::PARAM_INT);
        $stmt->execute();
        $object = $stmt->fetchObject(get_called_class());
        return ($format === false ? $object : (array)$object);
    }

    /**
     * @param string $q
     * @param array $cols
     * @param bool $all
     * @return bool or Object or array
     */
    public static function select($q, $cols=[], $all=false)
    {
        self::getDB();
        try {
            $handler = self::$db->prepare($q);
            if ($cols) {
                self::bindParams($handler, $cols);
            }
            $handler->execute();
            if ($all !== false) {
                $items = $handler->fetchAll(PDO::FETCH_ASSOC);
            } else {
                $modelName = get_called_class();
                $items = $handler->fetchObject($modelName);
            }
            self::$queries[] = [
                'query' => $q,
                'vars'  => (is_array($cols) ? implode(", ", $cols) : null),
                'time'  => date('d-m-Y H:i:s'),
            ];
        } catch (PDOException $e)
        {

        }

        return ($items ? $items : false);
    }

    /**
     * Delete record from DB.
     * @param string $cols
     * @return mixed
     */
    public static function delete($cols)
    {
        self::getDB();
        $first = true;
        $q = "DELETE FROM `" . static::TABLE . "` WHERE ";
        foreach ($cols as $col => $val) {
            $q .= ($first !== true ? " AND " : null);
            $q .= '`' . $col . '` = :' . $col;
            if ($first === true)
                $first = false;
        }
        $handler = self::$db->prepare($q);
        self::bindParams($handler, $cols);
        $handler->execute();
        return $handler->rowCount();
    }

    /**
     * @param array $result
     * @param string $sortByCol
     * @return array
     */
    public static function keyBy($result, $sortByCol)
    {
        if (empty($result)) {
            return false;
        }
        $array = [];
        foreach ($result as $key => $values)
        {
            if (array_key_exists($sortByCol, $values)) {
                $array[$values[$sortByCol]] = $values;
            }
        }
        return (count($array) ? $array : false);
    }

    /**
     * Gives all record from model
     * @param array $cols
     * @param string|null $order
     * @return mixed
     */
    public static function all($cols=[], $order=null)
    {
        $dbCols = null;
        if (is_array($cols) && count($cols)) {
            $dbCols = '`' . implode('`, `', $cols) . '`';
        }
        $q = "SELECT " . (!empty($dbCols) ? $dbCols : "*") . " FROM `" . static::TABLE . "`"
            . (static::DELETED === true ? " WHERE deleted_at IS NULL" : null)
            . (!empty($order) ? " ORDER by " . $order : null);
        $stmt = self::$db->prepare($q);
        $stmt->execute();
        return $stmt->fetchAll(PDO::FETCH_CLASS, get_called_class());
    }

    /**
     * Give a simpel list for a dropdown
     * @param (string) $col1
     * @param (string) $col2
     * @return mixed
     */
    public static function dropdown($col1, $col2)
    {
        $q = "SELECT `" . $col1 . "`, `" . $col2 . "` FROM `" . static::TABLE . "`"
            . (static::DELETED === true ? " WHERE deleted_at IS NULL" : null);
        $stmt = self::$db->prepare($q);
        $stmt->execute();
        return $stmt->fetchAll(PDO::FETCH_KEY_PAIR);
    }

    /**
     * Create a new object or Update object and save the object.
     * @param array $data
     * @return mixed
     */
    public static function updateOrCreate($data)
    {
        if (!empty($data['id'])) {
            $object = self::find($data['id']);
        } else {
            $object = self::createObject();
        }
        return $object->fillOutObject($data)->save();
    }

    /**
     * Fill the object with the data
     * @param array $data
     * @return $this
     */
    public function fillOutObject($data)
    {
        if (is_array($data)) {
            foreach ($this as $name => $oldValue) {
                if (array_key_exists($name, $data)) {
                    $this->$name = (isset($data[$name]) ? $data[$name] : null);
                }
            }
        }
        return $this;
    }

    /**
     * Save object to the database
     * @param bool $log
     * @param bool $returnObject
     * @return bool
     */
    public function save($log=true, $returnObject=true)
    {
        $now = date('Y-m-d H:i:s');
        $insert = false;
        if (!array_key_exists(static::$primaryKey, $this)) {
            $insert = true;
        }

        /**
         * when $insert = true then insert record
         * when $insert = false then update record
         */
        $q = null;
        if ($insert !== false) {
            if (static::TIMESTAMPS === true) {
                $this->__set('created_at', $now);
                $this->__set('updated_at', $now);
            }
            if (static::USER === true && !empty(\Login::getUserId())) {
                $this->__SET('created_by', \Login::getUserId());
                $this->__SET('updated_by', \Login::getUserId());
            }
            $q = $this->insert();
        } else {
            if (static::TIMESTAMPS === true) {
                $this->__set('updated_at', $now);
            }
            if (static::USER === true && !empty(\Login::getUserId())) {
                $this->__SET('updated_by', \Login::getUserId());
            }
            $q = $this->update();
        }

        /**
         *  Run query
         */
        $id = null;
        try {
            $handler = self::$db->prepare($q);
            self::bindParams($handler, $this);
            $handler->execute();
            $key = static::$primaryKey;
            if ($insert === true) {
                $this->$key = self::$db->lastInsertId();
            }
            $handler = null;
            self::$queries[] = [
                'query' => $q,
                'time'  => $now,
            ];
            //  Log action
            if ($log === true && !empty(\Login::getUserId())) {
                Sys_log::logAction($this->$key, get_called_class(), ($insert !== false ? 'create' : 'edit'));
            }

            //  Return object
            if ($returnObject === true) {
                return self::find($this->$key);
            } else {
                return true;
            }
        } catch (PDOException $e)
        {

        }
        return false;
    }

    /**
     * Save form translations
     * @param array $translation
     */
    public function saveTranslations(array $translation)
    {}

    /**
     * create insert query from object
     * @return string
     */
    private function insert()
    {
        $values = $cols = null;
        $q = "INSERT INTO " . static::TABLE;
        foreach ($this as $col => $val) {
            if (!in_array($col, ['primaryKey', 'deleted_at'])) {
                $cols .= (strlen($cols) ? ", " : null) . "`" . $col . "`";
                $values .= (strlen($values) ? ", " : null) . ":" . $col;
            }
        }
        /*if (static::TIMESTAMPS === true) {
            $cols   .= ", `created_at`, `updated_at`";
            $values .= ", :created_at, :updated_at";
        }
        if (static::USER === true && !empty(\Login::getUserId())) {
            $cols   .= ", `created_by`, `updated_by`";
            $values .= ", :created_by, :updated_by";
        }*/
        $q .= "(" . $cols . ") VALUES (" . $values . ")";
        return $q;
    }

    /**
     * create update query from object
     * @return string
     */
    private function update()
    {
        $first = true;
        $q = "UPDATE `" . static::TABLE . "` SET ";
        foreach ($this as $col => $val) {
            if (!in_array($col, ['primaryKey', 'id'])) {
                $q .= ($first !== true ? ", " : null);
                $q .= '`' . $col . '` = :' . $col;
                if ($first === true)
                    $first = false;
            }
        }
        
        $q .= " WHERE `" . static::$primaryKey . "` = :" . static::$primaryKey;
        return $q;
    }

    /**
     * @param $handler
     * @param $cols
     * @return mixed
     */
    private static function bindParams($handler, $cols)
    {
        foreach ($cols as $col => &$val) {
            if ($col != 'primaryKey') {
                if (is_int($val)) {
                    $handler->bindParam($col, $val, PDO::PARAM_INT);
                } elseif (is_null($val)) {
                    $handler->bindParam($col, $val, PDO::PARAM_NULL);
                } elseif (is_bool($val)) {
                    $handler->bindParam($col, $val, PDO::PARAM_BOOL);
                } else {
                    $handler->bindParam($col, $val, PDO::PARAM_STR);
                }
            }
        }
        return $handler;
    }

    /**
     * Create a new object
     * @return mixed
     */
    private static function createObject()
    {
        $q = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = :table";
        $stmt = self::$db->prepare($q);
        $stmt->bindValue(':table', static::TABLE, PDO::PARAM_STR);
        $stmt->execute();
        $object = new Static();
        while($row = $stmt->fetch(PDO::FETCH_ASSOC)){
            if (!in_array($row['COLUMN_NAME'], [static::$primaryKey, 'deleted_at'])) {
                $object->__set($row['COLUMN_NAME'], null);
            }
        }
        return $object;
    }

    /**
     * Get the PDO database connection
     * @return mixed
     */
    protected static function getDB()
    {
        if (!empty(self::$db)) {
            return;
        }
    
        $dsn = 'mysql:host=' . getenv('DB_HOST') . ';dbname=' . getenv('DB_DATABASE') . ';charset=utf8';
        self::$db = new PDO($dsn, getenv('DB_USERNAME'), getenv('DB_PASSWORD'));
    
        // Throw an Exception when an error occurs
        self::$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
        return self::$db;
    }

}`

**Comment by daveh** [comment]
In your select method, you're catching an exception but then not doing anything with it:

```
} catch (PDOException $e)
{

}
```

I wouldn't recommend doing that, as you'll lose any Exception information if an Exception occurs.

Also, in a control statement where you have a boolean variable, you don't need to explicitly compare it to false like this:

`if ($all !== false) {`

Instead, you can just do this:

`if ($all) {`

**Comment by telemoes** [comment]
`} catch (PDOException $e)
{

}`

yeah i lnow that i must do it everytime i think i do it later.

`if ($all !== false) {

Instead, you can just do this:

if ($all) {`

i Know that but with !== i check its a real boolean

**Comment by tejkweku** [comment]
Hello, I have a weird routing issue. Below is the full list of routes

```
$router->add('', ['controller' => 'Home', 'action' => 'index']);
$router->add('home/index', ['controller' => 'Home', 'action' => 'index']);
$router->add('home/contact', ['controller' => 'Home', 'action' => 'contact']);
$router->add('services', ['controller' => 'Services', 'action' => 'index']);
```

In the views, I set the ```href``` attributes of ```<a>``` tags in the following manner:

```
<a href="home/index">  <!-- To go to the home's index page -->
<a href="home/contact">  <!-- To go to the contact page -->
```

After the first page load, every link routes directly to the set controller and executes the set action; however, after selecting a link that invokes a controller with/without other parameters, every next route selected now includes the the full url of the previous link clicked (excluding the last parameter) and the full url of the new link clicked. 

For example, if the current url in address bar is `localhost/php-mvc/home/index`, clicking `<a href="contact">` routes to `localhost/php-mvc/home/contact`. Now clicking the services link would route to `localhost/php-mvc/home/contact/services`.

I need a way out. Also, the `public `folder is located in the root directory of the `htdocs `folder

**Comment by daveh** [comment]
@tej-kweku - it's because your links don't start with a slash, so they're relative to the folder they're in. If you start them with a slash:

```
<a href="/home/index">
<a href="/home/contact">
```

then they'll be relative to the site's root and will work no matter what the current URL.

**Comment by tej-kweku** [comment]
@daveh it also includes links that do not begin with backslashes.

**Comment by tejkweku** [comment]
'@daveh got it

**Comment by alturic** [comment]
@daveh Any update on when a new version of the course will come out? Eagerly awaiting.

**Comment by daveh** [comment]
@alturic Working on it as much as I can, but I am having various setbacks at the moment - no ETA I'm afraid but I'll be doing it as soon as I can! Thank you for your continued interest!
