### ISSUE TITLE
question about login/logout

### ISSUE THREAD

**Issue by ghost** [daveh/php-mvc#26]
have can I create login/logout action for admin/users?
is there any package in the composer for this?
Thank you.

**Comment by daveh** [comment]
I cover this in [the follow up course](https://www.udemy.com/php-mvc-login/?couponCode=MVCPA1) to the one that this framework is based on, alternatively there are [many packages available in Packagist](https://packagist.org/?q=login) that offer login and logout, which you can install using Composer.

**Comment by ghost** [comment]
thank you very much
