### ISSUE TITLE
linking css files

### ISSUE THREAD

**Issue by pantiru93** [daveh/php-mvc#27]
Hi Dave,

I am using your MVC in a personal project and it is awesome! Still, I have only one issue that I'm struggling for and I can't really find a solution.

I have this following structure:

```
/home/sportpla/public_html
/home/sportpla/public_html/index.php
/home/sportpla/public_html/css
/home/sportpla/admin
/home/sportpla/admin/index.php
/home/sportpla/admin/css
/home/sportpla/app
```
I the public_html folder I have the main website, and in the admin folder I have the admin area.
Right now, I have duplicated the css folder for both websites. So, I am trying to move the css folder at the same level with the app folder and link them from there. I tried using "../document root" in order to get there, but it did not work. 

Would you please let me know if there is anything that is restricting access to subfolders?

Thank you,
Cosmin

**Comment by daveh** [comment]
Hi Cosmin,

thank you for your interest in my framework!

The only publicly-accessible folder is the public (or public_html in your example) one. So you won't be able to link to files outside of this folder in HTML. You'd need to have them in a subfolder of the public_html folder, for example:

`/home/sportpla/public_html/css/admin/styles.css`

which you could link to in HTML with this:

`<link rel="stylesheet" type="text/css" href="/css/admin/styles.css">`

Is that what you meant?

Cheers,
Dave
