### ISSUE TITLE
My html and css won't link 

### ISSUE THREAD

**Issue by Shay2k00** [daveh/php-mvc#28]
Here is my HTML:
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel=”stylesheet” type=”text/css” href=”style.css” />
    <title></title>
  </head>
  <body>
    <h1>
      This is a heading
    </h1>
    <p>
      This is a paragraph.
    </p>
    <h2>
      Hi
    </h2>
  </body>
</html>

Here is my CSS:
h1 {
      border-top-style: dotted;
    border-right-style: solid;
    border-bottom-style: dotted;
    border-left-style: solid;
 }

What am I doing wrong? Please help me.

**Comment by Shay2k00** [comment]
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel=”stylesheet” type=”text/css” href=”style.css” />
    <title></title>
  </head>
  <body>
    <h1>
      This is a heading
    </h1>
    <p>
      This is a paragraph.
    </p>
    <h2>
      Hi
    </h2>
  </body>
</html>`

**Comment by daveh** [comment]
Is your CSS in a separate file? It needs to be in the public folder. You can then link to it like this, for example if you have a file public/css/styles.css:

```
<head>
  <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>
```
