### ISSUE TITLE
about licence

### ISSUE THREAD

**Issue by lablnet** [daveh/php-mvc#29]
Hello sire i follow your tutorials on uderny and make router class and i change controller,modals,error,view class with my custom codes can its allow use this router class and make my own framework?
is i need add @auther yourname?
thanks

**Comment by daveh** [comment]
Hi,

the code in this repository is under [the MIT license](https://github.com/daveh/php-mvc/blob/master/LICENSE), so you're free to use it however you like. No, you don't need to add me as an author.

Thank you for asking!

Best wishes,
Dave

**Comment by lablnet** [comment]
@daveh Thanks you so much for replying

**Comment by lablnet** [comment]
Hay sire I done this here is framework
http://github.com/Softhub99/Zest

**Comment by daveh** [comment]
Looks good! Good luck with it! :+1:
