### ISSUE TITLE
Strange things with $_SESSION

### ISSUE THREAD

**Issue by funilrys** [daveh/php-mvc#3]
I wanted to have a look at this cause I wanted to learn the concept of OOP & MVC at the same time.
So I tried to implement an old (PHP 5.6) procedural project.
I noticed that session only works per controller/view is it normal or I don't understand the concept ? 

For exemple if I set
 ``` php
$_SESSION['hello'] = 'world'
 ```
 in the Home (indexAction) controller I can't handle it in Home(forgotPasswordAction) ...

I try to debug or find an explanation for more than 4 hours but can't understand where the problem is and I hope that you may explain it.

The same thing if I set 
 ``` php
$_SESSION['hello'] = 'world'
 ```
under 
 ``` php
View::renderTemplate('Home/index.html.twig')
 ```
 I can't get it under 
 ``` php
View::renderTemplate('Home/forgot-password.html.twig')
 ```
 with the global variable

 ``` php
$twig->addGlobal("session", $_SESSION);
 ```

**Comment by funilrys** [comment]
Just found after +6 hours :+1: sorry gonna close this and by the way why don't you propose other solution than change root ? :)

**Comment by funilrys** [comment]
Finally not solved ... I take my day to search..

**Comment by daveh** [comment]
Hi,

where are you calling `session_start()`? You need to call this in every request, so I would recommend calling it in the [front controller](https://github.com/daveh/php-mvc/blob/master/public/index.php).

Your method for adding the session to Twig is what I would do though, and should work. Could this be related to `session_start()` perhaps?

**Comment by funilrys** [comment]
Thanks for pointing out ! 
I currently use a function that use the following before starting the session and I noticed that the session name has invalid characters.

``` php
session_set_cookie_params()        
session_name($sessionName);
```

Thanks again and I wish you a great day/night.

**Comment by daveh** [comment]
No problem, glad you got it working.
