### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by mbelatar** [daveh/php-mvc#31]
I'm currently using only one database, but now I have to add ONE MORE (Postgresql)

**Comment by mbelatar** [comment]
Current Database is Mysql

**Comment by daveh** [comment]
Hi,

do you want to use two databases at once? In that case you'll have to modify the framework to allow that, as currently it only supports connecting to one. For example, in the Core\Model class, add a static connections property, and change the getDB method so a database name is passed in:

```
/**
 * Connections
 *
 * @var array
 */
protected static $connections = [];

/**
 * Get the PDO database connection
 *
 * @param string $name The db name
 *
 * @return mixed
 */
protected static function getDB($name)
{
    if (static::$connections[$name] === null) {
        $dsn = 'mysql:host=' . Config::DB_HOST . ';dbname=' . Config::DB_NAME . ';charset=utf8';
        static::$connections[$name] = new PDO($dsn, Config::DB_USER, Config::DB_PASSWORD);

        // Throw an Exception when an error occurs
        static::$connections[$name]->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }

    return static::$connections[$name];
}
```

You'll have to change the way the config settings are used, as these will be different for each database, and the database type identifier used in the dsn (I haven't included this in the above example to keep it simple but it shouldn't be difficult to implement, depending on how you're doing it)

Is that what you mean?

**Comment by mbelatar** [comment]
Yes Sir, Thank you very much

**Comment by mbelatar** [comment]
je propose cette solution : 

/App/Config/db/mysql.php

`

return (object) array(
	'driver' => 'mysql',
	'host' => '',
	'username' => '',
	'password' => '',
	'dbname' => '',
	'charset' => ''
);`

/App/Config/db/pgsql_cache.php

`

return (object) array(
	'driver' => 'pgsql',
	'host' => '',
	'username' => '',
	'password' => '',
	'dbname' => ''
);`

/Core/Config.php

`

namespace Core;
use PDO;

class Config
{
	public function __construct()
	{
		$this->_initTime();
		$this->_initConfig();
		$this->_initDb();
	}
    protected function _initDb()
    {

		$mysql_params		= require(APPLICATION_PATH.DS.'Config'.DS.'db'.DS.'mysql.php');
		$pgsql_data_params	= require(APPLICATION_PATH.DS.'Config'.DS.'db'.DS.'pgsql_data.php');
		$pgsql_infos_params	= require(APPLICATION_PATH.DS.'Config'.DS.'db'.DS.'pgsql_infos.php');
		$pgsql_cache_params	= require(APPLICATION_PATH.DS.'Config'.DS.'db'.DS.'pgsql_cache.php');
		$pgsql_suggests_params	= require(APPLICATION_PATH.DS.'Config'.DS.'db'.DS.'pgsql_suggests.php');

        Registry::set('mysql_db', $mysql_params);
        Registry::set('pgsql_data', $pgsql_data_params);
        Registry::set('pgsql_cache', $pgsql_cache_params);
        Registry::set('pgsql_infos', $pgsql_infos_params);
        Registry::set('pgsql_suggests', $pgsql_suggests_params);
	}
	public function _initConfig()
    {
		$config = require(APPLICATION_PATH.DS.'Config'.DS.'config.php');
		Registry::set('config', $config);
		Registry::set('display_errors', $config['display_errors']);
	}
    protected function _initTime()
    {
        date_default_timezone_set('Africa/Casablanca');
    }
}`

/Core/Registry.php

`

namespace Core;

// take a look on this <green part> : 
// https://stackoverflow.com/questions/28730071/have-only-one-instance-of-a-class

class Registry extends \ArrayObject
{
	private static $_registryClassName = 'Core\Registry';
	private static $_registry = null;
    public static function getInstance()
    {
        if (self::$_registry === null) {
            self::init();
        }
        return self::$_registry;
    }
    public static function setInstance(Registry $registry)
    {
        if (self::$_registry !== null) {
            throw new \ErrorException('Registry is already initialized');
        }

        self::setClassName(get_class($registry));
        self::$_registry = $registry;
    }
    protected static function init()
    {
        self::setInstance(new self::$_registryClassName());
    }
    public static function setClassName($registryClassName = 'Zend_Registry')
    {
        if (self::$_registry !== null) {
            throw new \ErrorException('Registry is already initialized');
        }

        if (!is_string($registryClassName)) {
            throw new \ErrorException("Argument is not a class name");
        }


        self::$_registryClassName = $registryClassName;
    }
    public static function _unsetInstance()
    {
        self::$_registry = null;
    }
    public static function get($index)
    {
        $instance = self::getInstance();

        if (!$instance->offsetExists($index)) {
            throw new \ErrorException("No entry is registered for key '$index'");
        }

        return $instance->offsetGet($index);
    }
    public static function set($index, $value)
    {
        $instance = self::getInstance();
        $instance->offsetSet($index, $value);
    }
    public static function isRegistered($index)
    {
        if (self::$_registry === null) {
            return false;
        }
        return self::$_registry->offsetExists($index);
    }
    public function __construct($array = array(), $flags = parent::ARRAY_AS_PROPS)
    {
        parent::__construct($array, $flags);
    }
    public function offsetExists($index)
    {
        return array_key_exists($index, $this);
    }
}`

And finaly \Core\Model.php

`

namespace Core;

use PDO;
use Core\Config;

abstract class Model
{
	protected $_db;
	protected static function getDB($db_params_name)
	{
        static $db = array();
        if (!isset($db[$db_params_name]))
		{
			$db_params = Registry::get($db_params_name);
            $dsn = $db_params->driver.':host=' . $db_params->host . ';dbname=' . $db_params->dbname .(isset($db_params->charset)?';charset'.$db_params->charset:'');
            $db[$db_params_name] = new PDO($dsn, $db_params->username, $db_params->password);
			$pdoParams = array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES UTF8;');
            $db[$db_params_name]->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        }
        return $db[$db_params_name];
    }
}
`

Example Use :

/App/Model/Link.php

`

namespace App\Models;
use PDO;

class Link extends \Core\Model
{
    public static function getAll()
    {
        $db = static::getDB('pgsql_infos');
        $stmt = $db->query('SELECT * FROM links limit 1');
		return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
	public static function add($data)
	{
        $db = static::getDB('pgsql_infos');
		return $db->exec('insert into links ("host","url") VALUES (\''.pg_escape_string($data['host']).'\',\''.pg_escape_string($data['url']).'\')');
	}
}`

**Comment by mbelatar** [comment]
This what i did , now i can Use multiple Databases and servers on the same Project

**Comment by daveh** [comment]
Cool, thank you for sharing your solution! :+1:
