### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by mbelatar** [daveh/php-mvc#32]
Here is my Controller :

```
<?php

namespace App\Controllers;

class Hosts extends \Core\Controller
{
    public function IndexAction ()
    {
		$p = @$_GET['p'];
		$config = \Core\Registry::get('config');
		$count_query = \App\Models\Host::query("select count(*) from sites");
		$count_res = @$count_query[0]['count'];
    }
}
```

The Model :

```
<?php

namespace App\Models;
use PDO;

class Host extends \Core\Model
{
    public static function getAll()
    {
        $db = static::getDB('pgsql_infos');
        $stmt = $db->query('SELECT * FROM sites');
		return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
    public static function Query($q)
    {
        $db = static::getDB('pgsql_infos');
        $stmt = $db->query($q);
		return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
	public static function add($data)
	{
        $db = static::getDB('pgsql_infos');
		return $db->exec('insert into sites ("host","priority","enabled","language","domain","category") VALUES (\''.pg_escape_string($data['host']).'\',\''.pg_escape_string($data['priority']).'\',\''.pg_escape_string($data['enabled']).'\',\''.pg_escape_string($data['language']).'\',\''.pg_escape_string($data['domain']).'\',\''.pg_escape_string($data['category']).'\')');
	}
}
```

How can i impliments a pagination Class / Helper ?

**Comment by daveh** [comment]
Something like this perhaps?

```
<?php

/**
 * Paginator
 *
 * Data for selecting a page of records
 */
class Paginator
{
    /** 
     * Number of records to return
     * @var integer
     */
    public $limit;

    /** 
     * Number of records to skip before the page
     * @var integer
     */
    public $offset;

    /** 
     * Previous page number
     * @var integer
     */
    public $previous;

    /** 
     * Next page number
     * @var integer
     */
    public $next;

    /** 
     * Constructor
     *
     * @param integer $page Page number
     * @param integer $records_per_page Number of records per page
     * @param integer $total Total number of records
     *
     * @return void
     */
    public function __construct($page, $records_per_page, $total_records)
    {   
        $this->limit = $records_per_page;

        $page = filter_var($page, FILTER_VALIDATE_INT, [
            'options' => [
                'default'   => 1,
                'min_range' => 1
            ]
        ]);

        if ($page > 1) {
            $this->previous = $page - 1;
        }

        $total_pages = ceil($total_records / $records_per_page);

        if ($page < $total_pages) {
            $this->next = $page + 1;
        }

        $this->offset = $records_per_page * ($page - 1); 
    }   
}
```

Which you then call like this:

```
$paginator = new Paginator($_GET['page'] ?? 1, 4, Host::getTotal());
    
$data = Host::getPage($paginator->limit, $paginator->offset);
```

You need a `getTotal` method on a model to get the total number of records, along with a `getPage` method which does a SELECT using LIMIT and OFFSET based on the values from the paginator.

**Comment by mbelatar** [comment]
Thank you very much Sire 

This is what i did :

The controller :
`<?php

namespace App\Controllers;
use \Core\View;

class Hosts extends \Core\Controller
{
    public function IndexAction ()
    {
		$output = [];
		$p = (isset($this->route_params['p']) and is_numeric($this->route_params['p']) and $this->route_params['p']>0)?$this->route_params['p']:1;
		$q = (isset($_GET['q']))?$_GET['q']:'';
		$config = \Core\Registry::get('config');
		$rows_per_page = $config['pagination']['rows_per_page'];
		$count_query = \App\Models\Host::query("SELECT COUNT(*) FROM sites ".($q?"where host like('%$q%')":''));
		$rows_count = (isset($count_query[0]['count']))?$count_query[0]['count']:0;
		$offset = (is_numeric($p) and $p>0)?($p-1)*$rows_per_page:0;
		$total_pages = ceil($rows_count / $rows_per_page);

		$output['q'] = $q;
		$output['rows_per_page'] = $rows_per_page;
		$output['rows_count'] = $rows_count;
		$output['current_page'] = $p;
		$output['last_page'] = $total_pages;
		$output['pagination_path'] = "/hosts/";

		$data = \App\Models\Host::query("SELECT * FROM sites ".($q?"where host like('%$q%')":'')." order by id LIMIT ".$rows_per_page." OFFSET ".$offset);
		$output['data'] = $data;
		foreach($data as $d)
		{
			if(!$d['domain'])
			{
				$parse_url = parse_url("http://".$d['host']);
				$host = @$parse_url['host'];
				\App\Models\Host::query("update sites set domain = '".pg_escape_string(\Core\Domain::get_domain($host))."' where id =".$d['id']);
				if(!\Core\Domain::get_domain($host))
				{
					// \App\Models\Host::query("delete from sites where id =".$d['id']);	
				}
			}
		}
		View::renderTemplate('Hosts/index.html',$output);
    }
    public function EditAction ()
    {
		$output = [];
		$id = (isset($this->route_params['id']) and is_numeric($this->route_params['id']) and $this->route_params['id']>0)?$this->route_params['id']:0;
		if ($_SERVER['REQUEST_METHOD'] == 'POST')
		{
			$category = (isset($_POST['category']))?$_POST['category']:'';
			$host = (isset($_POST['host']))?$_POST['host']:'';
			$priority = (isset($_POST['priority']))?$_POST['priority']:'';
			$enabled = (isset($_POST['enabled']) and $_POST['enabled']==1)?1:0;
			$language = (isset($_POST['language']))?$_POST['language']:'';
			$domain = (isset($_POST['domain']))?$_POST['domain']:'';

			\App\Models\Host::query("
			UPDATE sites set 
			category='".pg_escape_string($category)."',
			host='".pg_escape_string($host)."',
			priority='".pg_escape_string($priority)."',
			enabled='".pg_escape_string($enabled)."',
			language='".pg_escape_string($language)."',
			domain='".pg_escape_string($domain)."'
			where id=".$id);
			
		}
		$config = \Core\Registry::get('config');
		$data = \App\Models\Host::query("SELECT * FROM sites where id=".$id);
		$output['data'] = $data;
		View::renderTemplate('Hosts/edit.html',$output);
    }
    public function EnableAction ()
    {
		$output = [];
		$id = (isset($this->route_params['id']) and is_numeric($this->route_params['id']) and $this->route_params['id']>0)?$this->route_params['id']:0;
		if ($_SERVER['REQUEST_METHOD'] == 'POST' and $id)
		{
			$enabled = (isset($_POST['val']) and $_POST['val']==1)?1:0;
			\App\Models\Host::query("
			UPDATE sites set 
			enabled='".pg_escape_string($enabled)."'
			where id=".$id);
			
		}
    }
}
`

The model :

`<?php

namespace App\Models;
use PDO;

class Host extends \Core\Model
{
    public static function getAll()
    {
        $db = static::getDB('pgsql_infos');
        $stmt = $db->query('SELECT * FROM sites');
		return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
    public static function Query($q)
    {
        $db = static::getDB('pgsql_infos');
        $stmt = $db->query($q);
		return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
	public static function add($data)
	{
        $db = static::getDB('pgsql_infos');
		return $db->exec('insert into sites ("host","priority","enabled","language","domain","category") VALUES (\''.pg_escape_string($data['host']).'\',\''.pg_escape_string($data['priority']).'\',\''.pg_escape_string($data['enabled']).'\',\''.pg_escape_string($data['language']).'\',\''.pg_escape_string($data['domain']).'\',\''.pg_escape_string($data['category']).'\')');
	}
}`


The View :


`{% extends "base.html" %}
{% block title %}Aught search engine - Hosts{% endblock %}
{% block body %}
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
		<div class="container">
		  <a class="navbar-brand mr-auto mr-lg-0" href="#">Odub.net</a>
		  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
			<span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item active">
				<a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="#">Notifications</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="#">Profile</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="#">Switch account</a>
			  </li>
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
				<div class="dropdown-menu" aria-labelledby="dropdown01">
				  <a class="dropdown-item" href="#">Action</a>
				  <a class="dropdown-item" href="#">Another action</a>
				  <a class="dropdown-item" href="#">Something else here</a>
				</div>
			  </li>
			</ul>
		  </div>
      </div>
    </nav>

    <div class="nav-scroller bg-white box-shadow">
      <nav class="nav nav-underline container">
        <a class="nav-link active" href="#">Dashboard</a>
        <a class="nav-link" href="#">
          Friends
          <span class="badge badge-pill bg-light align-text-bottom">27</span>
        </a>
        <a class="nav-link" href="#">Explore</a>
        <a class="nav-link" href="#">Suggestions</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
      </nav>
    </div>

	<main role="main" class="container">
	
      <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
        <img class="mr-3" src="/assets/brand/logo.svg" alt="" width="48" height="48">
        <div class="lh-100">
          <h6 class="mb-0 text-white lh-100">Managing Hosts</h6>
          <small>{{ rows_count }} Website</small>
        </div>
      </div>
		<div class="row">
			<div class="col-sm-12 col-md-10">
				<div class="">
					<p>
						Page <b>{{ current_page }}</b> of <b>{{ last_page }}</b>,
						of <b>{{ rows_count }}</b> row
					</p>
				</div>
			</div>
			<div class="col-sm-12 col-md-2">
				<div class="text-right">
					<form action="?">
					<input type="search" value="{{ q|e }}" name="q" class="form-control form-control-sm" placeholder="Search" aria-controls="example">
					</form>
				</div>
			</div>
		</div>
		<div class="my-3 p-3 bg-white rounded box-shadow">

			{% if rows_count == 0 %}
			No data
			{% else %}
			
			<table class="table table-sm table-bordered table-striped">
			  <thead>
				<tr>
				  <th scope="col">Host</th>
				  <th scope="col">Domain</th>
				  <th scope="col">Priority</th>
				  <th scope="col">Enabled</th>
				  <th scope="col">Language</th>
				  <th scope="col">Category</th>
				  <th scope="col">Last visit</th>
				</tr>
			  </thead>
			  <tbody>
				{% for hit in data %}
				<tr>
				  <td><a href="http://{{ hit.host }}" target="_blank">{{ hit.host }}</a></td>
				  <td>{{ hit.domain }}</td>
				  <td>{{ hit.priority }}</td>
				  <td><input type="checkbox" data-id="{{ hit.id }}" class="enabler" {% if hit.enabled=="1" %}checked{% endif %}></td>
				  <td>{{ hit.language }}</td>
				  <td>{{ hit.category }}</td>
				  <td>{{ hit.lastvisit }}</td>
				  <td class="text-center"><a href="/hosts/edit/{{ hit.id }}" class="btn btn-sm btn-primary">Edit</a></td>
				</tr>
				{% endfor %}
			  </tbody>
			</table>
			<script>
			$( document ).ready(function() {
				$(".enabler").change(function () {
					var checked = "0";
					if($(this).prop('checked') == true){
						checked = "1";
					};
					$.ajax({
						type: "POST",
						url: "/hosts/stat/"+$(this).attr("data-id"),
						async: true,
						data: {
							val: checked
						},
						success: function (msg) {
							//alert('Success');
							if (msg != 'success') {
								//alert('Fail');
							}
						}
					});
				});
			});
			</script>
			{% spaceless %}
				{% if last_page > 1 %}

					{# the number of first and last pages to be displayed #}
					{% set showAlwaysFirstAndLast = false %}
					{% set extremePagesLimit = 4 %}
					{# the number of pages that are displayed around the active page #}
					{% set nearbyPagesLimit = 4 %}

					<nav aria-label="">
						<ul class="pagination pagination-sm">
						{% if current_page > 1 %}
							<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ current_page-1 }}{% if q %}?q={{ q }}{% endif %}">&larr;</a></li>

							{% for i in range(1, extremePagesLimit) if ( i < current_page - nearbyPagesLimit ) %}
								<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ i }}{% if q %}?q={{ q }}{% endif %}">{{ i }}</a></li>
							{% endfor %}

							{% if extremePagesLimit + 1 < current_page - nearbyPagesLimit %}
								<li class="disabled"><a class="page-link" href="#">...</a></li>
							{% endif %}

							{% for i in range(current_page-nearbyPagesLimit, current_page-1) if ( i > 0 ) %}
								<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ i }}{% if q %}?q={{ q }}{% endif %}">{{ i }}</a></li>
							{% endfor %}
						{% elseif showAlwaysFirstAndLast %}
							<li class="page-item"><a class="page-link" href="#">&larr;</a></li>
						{% endif %}

						<li class=""><a class="page-link disabled" href="#">{{ current_page }}</a></li>

						{% if current_page < last_page %}
							{% for i in range(current_page+1, current_page + nearbyPagesLimit) if ( i <= last_page ) %}
								<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ i }}{% if q %}?q={{ q }}{% endif %}">{{ i }}</a></li>
							{% endfor %}

							{% if  (last_page - extremePagesLimit) > (current_page + nearbyPagesLimit) %}
							   <li class="disabled"><a class="page-link" href="#">...</a></li>
							{% endif %}

							{% for i in range(last_page - extremePagesLimit+1, last_page) if ( i > current_page + nearbyPagesLimit ) %}
							   <li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ i }}{% if q %}?q={{ q }}{% endif %}">{{ i }}</a></li>
							{% endfor %}

							<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ current_page+1 }}{% if q %}?q={{ q }}{% endif %}">&rarr;</a></li>
						{% elseif showAlwaysFirstAndLast %}
							<li class="page-item"><a class="page-link" href="{{ pagination_path }}{{ current_page+1 }}{% if q %}?q={{ q }}{% endif %}">&rarr;</a></li>
						{% endif %}
						</ul>
					</nav>
				{% endif %}
			{% endspaceless %}
			{% endif %}
		</div>
	</main>
{% endblock %}`


Im based on twig.

**Comment by mbelatar** [comment]
I will try to create a class for this and share it using your pagination class
