### ISSUE TITLE
Ajax request, return json

### ISSUE THREAD

**Issue by phphil** [daveh/php-mvc#34]
Let's say I would like to collect user data from my database. I get this information with an AJAX request and send the data back to the browser as JSON. My question is “what the best solution of sending back JSON data?” This is how I did it. Is this a good solution or would you suggest something else?

userController:
```
/**
 * Show edit model of specific users
 *
 * @return string
 */
public function editAction()
{
    $users = users::findById($_POST['id']);
    
    if ($users) {

        $myJSON = json_encode($users);

        View::renderTemplate('Admin/users/edit.html', [
            'json' => $myJSON
        ]);
    }
}
```

JSON view:
`{{ json | raw }}`

**Comment by daveh** [comment]
That's a good solution, no problem with that. You could also do the JSON encoding in the view if you wanted, using the [Twig json_encode filter](https://twig.symfony.com/doc/2.x/filters/json_encode.html):

```
/**
 * Show edit model of specific users
 *
 * @return string
 */
public function editAction()
{
    $users = users::findById($_POST['id']);
    
    if ($users) {

        View::renderTemplate('Admin/users/edit.html', [
            'data' => $users
        ]);
    }
}
```

JSON view:
`{{ data | json_encode() }}`

That makes the controller code a bit shorter, but it's up to you. You could probably also remove the if block in the controller action, and deal with no data being returned in the client instead:

```
public function editAction()
{
    View::renderTemplate('Admin/users/edit.html', [
        'data' => users::findById($_POST['id']);
    ]);
}
```
