### ISSUE TITLE
Switching between subdomains, requires re-login

### ISSUE THREAD

**Issue by InfraRedApple** [daveh/php-mvc#35]
If you are logged into mydomain.com and then change the url to www.mydomain.com, you are asked to re-login when navigating to a protected page.

**Comment by daveh** [comment]
You can change the domain of the session cookie in the php.ini file, in the [session.cookie_domain](http://php.net/manual/en/session.configuration.php#ini.session.cookie-domain) setting. If you set it to ".example.com", then it'll be valid for all subdomains of that domain, including "www". If you don't have access to the php.ini file, then you can achieve the same using the [session_set_cookie_params](http://php.net/manual/en/function.session-set-cookie-params.php) function.
