### ISSUE TITLE
Using the id inside a controller class

### ISSUE THREAD

**Issue by Mooeep** [daveh/php-mvc#36]
Hello daveh, I am having trouble using the id from the URL correctly.
I can get the id with  $id = $this->route_params['id']; 
I need it in my Class App\Controller\User.
However since the class extends \Core\Controller i either get an error message for using $this, or if I instantiated it, it need the $route_params to be constructed which comes up as null.

Basically I want to get the user with the id written in the url. 
This is the function inside the app/controller class:

public function retrieveAction()
    {
        $id = $this->route_params['id'];
        settype($id, "integer");
        var_dump($id);
        $identifier = $id;
        var_dump($identifier);

        $user = Models\User::retrieve($identifier);

        return $user;
    }

and this is the function inside my app/model class:

public static function retrieve($identifier) {
        $conn = static::getDB();
        $query = 'SELECT * FROM `User` WHERE `identifier` = :identifier';
        $stmt = $conn->prepare($query);
        $stmt->bindParam(':identifier', $identifier, PDO::PARAM_INT);
        $stmt->execute();

        $result = $stmt->fetch(PDO::FETCH_ASSOC);

        return new User((int)$result['identifier'], $result['name'], $result['password']);
    }

**Comment by daveh** [comment]
Hi Caroline,

using this inside your controller action should work:

`$id = $this->route_params['id'];`

You need a route that contains the ID variable, for example:

`$router->add('{controller}/{action}/{id:\d+}');`

What error message are you getting exactly?

**Comment by Mooeep** [comment]
I have both of that. If I type in an integer e.g. 1 or 2 I get the User I want.
My guess is, that this: $test2 = new User ($route_params);
Does not work, as $route_params has no value in it, if my var_dump of $identifier inside the function gives back: C:\Program Files (x86)\Ampps\www\WaWi\App\Controllers\User.php:27:int 0

The error message is a bit confusing as it simply says: Fatal error: Uncaught Exception: Invalid Name. in C:\Program Files (x86)\Ampps\www\WaWi\App\Models\User.php on line 44.

This line simply says to throw an error if the name is not a string.

**Comment by daveh** [comment]
What URL gives you the error?

**Comment by Mooeep** [comment]
http://localhost/user/1/retrieve

**Comment by daveh** [comment]
Please could you also let me know your routes (from public/index.php) and also an example of a URL that _does_ work?

**Comment by Mooeep** [comment]
I use the one from your tutorial. 
The URL does work as intended, otherwise it would tell me "No routes matched". I just have the model setup and am trying out different controllers now. No view configured yet, I thought it best to see if the controllers work.

the routes from public/index.php:

//Add the routes
$router->add('', ['controller' => 'Home', 'action' => 'index']);
$router->add('{controller}/{action}');
$router->add('{controller}/{id:\d+}/{action}');
$router->add('admin/{controller}/{action}', ['namespace' => 'Admin']);

**Comment by Mooeep** [comment]
Might it be, because the $route_params is empty in $test2 = new User ($route_params);?
If yes, how can I change that?

**Comment by Mooeep** [comment]
If I var_dump the $user instead of returning it inside the function I get the right data from the database, I can even change the number in the URL and get dumped the other Users I have created.

So this works: 
public function retrieveAction()
    {
        $id = $this->route_params['id'];
        settype($id, "integer");
        $identifier = $id;

        $user = Models\User::retrieve($identifier);

        var_dump($user);
    }

Just the "displaying" of that function does not work.

**Comment by daveh** [comment]
Sorry I'm a bit confused, where have you got this line of code:

`$test2 = new User ($route_params);`

The router is where new controller objects are created, and the `$route_params` variable is always passed in.

By the way, are you following the tutorial on Udemy or are you just using the framework from Github?

**Comment by telemoes** [comment]
I did this:

```
class BlogController extends Controller
{
    const MAX_PHOTOS = 4;

    protected   $route_params = null;
    private     $blogTags = [];
    public      $data = [];

    public function __construct(array $route_params)
    {
        parent::__construct($route_params);
        parent::geTranslations();
    }
```
I can in the hole controller use $this->route_params['key'] this works fine check de core controller and your controllers

**Comment by Mooeep** [comment]
It was my bad. I tried to call the object outside of the class, because I thought this way I could make controllers first, test them and then care about the view. However that does not work. Making them  both at the same time now or testing with var_dump.
Thank you for your help :)
