### ISSUE TITLE
Admin routing

### ISSUE THREAD

**Issue by tokidevelop** [daveh/php-mvc#37]
Hello. 
How is it possible to route frontend (public) and backend controllers.
My folder structure looks like
-- Modules <--  modules/plugins for cms
---- CMS
------ PageController.php
------ AssetsController.php
------ SecurityController.php
----- DASHBOARD
------ DashboardController.php

I want it to route like "sitename.com/admin/cms/{controller}" and "sitename.com/admin/dashboard/{action}"

Any suggestions?
Kind regards

**Comment by daveh** [comment]
Hi,

you can put whatever segments you like in the routes, and you can also specify namespaces. If your classes inside each folder are in corresponding namespaces, you could do this:

```
$router->add('admin/cms/{controller}/{action}', ['namespace' => 'CMS']);
$router->add('admin/dashboard/{controller}/{action}', ['namespace' => 'DASHBOARD']);
```

**Comment by telemoes** [comment]
Hi i have a other soulution for your admin.
What i did..

`$router->add('pages/create');`
And in the controller a check if admin is logon.

Greetings

**Comment by tokidevelop** [comment]
Thanks telemoes but thats not the kind of solution im looking for..
@daveh , I get the message "No routes matched". Looking into the code for a few hours and made some changes but still cant get the latest param into the controller..

Index.php
`$oRouter = new core\router();
$oRouter->add('admin/cms/{controller}/{action}', ['namespace' => 'module\cms']);
$oRouter->dispatch($_SERVER[ 'QUERY_STRING' ]);`

var_dump on $this->m_aParams returns empty array..

_module/cms/pagecontroller.php
`namespace module\cms;

class page extends \core\controller {

    public function indexAction() {
        return 'Admin cms page :)';
    }

}`

autoloader.php
`<?php 
namespace core;

require BASE_DIR . '/_core/class/filesystem.php';

class autoload {

    /**
     * @param $p_sClassName
     * @throws \Exception
     */
    public static function load($p_sClassName) {
        $aClass = explode('\\', $p_sClassName);
        if ($aClass[ 0 ] == 'core') {
            $p_sFileName = BASE_DIR . '/_core/class/' . implode('/', array_slice($aClass, 1)) . '.php';

        } else if ($aClass[ 0 ] == 'module') {
            $p_sFileName = BASE_DIR . '/_module/' . implode('/', array_slice($aClass, 1)) . '.php';
        } else {
            $p_sFileName = BASE_DIR . '/' . str_replace('\\', '/', $p_sClassName) . '.php';
        }

        var_dump($p_sFileName);
        if (filesystem::fileExists($p_sFileName)) {
            include $p_sFileName;
        } else {
            throw new \Exception('File "' . $p_sFileName . '" Not Found.');
        }

    }`

**Comment by daveh** [comment]
Please can you list your routes, and the URL that you're trying to match?

**Comment by tokidevelop** [comment]
Url trying to match is:
HTTP://localhost/framework/admin/cms/page

At the moment i only have one route
$oRouter = new core\router(); 
$oRouter->add('admin/cms/{controller}/{action}', ['namespace' => 'module\cms']);

**Comment by daveh** [comment]
If you've got the framework in a subfolder of the web root, you need to add an .htaccess file to that subfolder (framework/.htaccess) containing the following:

```
RewriteEngine On
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) public/$1 [L]
```
And also add a RewriteBase directive to the public/.htaccess file:

```
RewriteEngine On
RewriteBase /framework
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteCond %{REQUEST_FILENAME} !-l 
RewriteRule ^(.*)$ index.php?$1 [L,QSA]
```

Does that fix it?

**Comment by tokidevelop** [comment]
/framework is not a subdirectory but the name of my virtual server from wamp. :)
When i change the route to 
`->add('admin/cms/{controller}', ['action' => 'index']);`
then the url /framework/admin/cms/page works. So why is it not working with the namespace?

**Comment by daveh** [comment]
The router will try and load the class that's in that namespace, using PSR-4 autoloading, so it expects the class to be in a folder with the same name as the namespace. Please can you post your controller code?

**Comment by tokidevelop** [comment]
My controller code is original hadnt made any changes (yet)
`<?php

namespace core;

abstract class controller {

    /**
     * Parameters from the matched routes
     * @var array
     */
    protected $m_aParams = [];

    /**
     * core_controller constructor.
     *
     * @param $p_sParams
     */
    public function __construct($p_sParams) {
        $this->m_aParams = $p_sParams;
    }

    /**
     * @param $p_sName
     * @param $p_aArgs
     * @throws Exception
     */
    public function __call($p_sName, $p_aArgs) {
        $sMethod = $p_sName . 'Action';
        if(method_exists($this, $sMethod)){
            if($this->renderBefore() !== false){
                call_user_func_array([$this, $sMethod], $p_aArgs);
                $this->renderAfter();
            }
        } else {
            throw new Exception('Method "'.$sMethod.'" not found in controller "'.get_class($this).'"');
        }
    }

    /**
     * Before filter, called before an action method
     */
    protected function renderBefore(){}

    /**
     * After filter, called after an action method
     */
    protected function renderAfter(){}

}

I'm use my own autoloading class, that i think is not PSR-4 compatibel. All my classes are in the right folders using the same tree e.g. `namespace core\module class dashboard extends core\controller`
Folder structure is: `_core/module/dashboard/dashboard.php`

My custom autoloader:
`<?php

namespace core;

require BASE_DIR . '/_core/class/filesystem.php';

class autoload {

    /**
     * @param $p_sClassName
     * @throws \Exception
     */
    public static function load($p_sClassName) {
        $aClass = explode('\\', strtolower($p_sClassName));
        if ($aClass[ 0 ] == 'module') {
            $sFileName = BASE_DIR . '/_module/' . implode('/', array_slice($aClass, 1)) . '.php';
        } else if ($aClass[ 0 ] == 'core') {
            $sFileName = BASE_DIR . '/_core/class/' . implode('/', array_slice($aClass, 1)) . '.php';
        } else {
            $sFileName = BASE_DIR . '/' . implode('/', array_slice($aClass, 1)) . '.php';
        }
        if (filesystem::fileExists($sFileName)) {
            include $sFileName;
        } else {
            throw new \Exception('File "' . $sFileName . '" Not Found.');
        }

    }`

**Comment by daveh** [comment]
So where are you calling your autoloader's `load` method? In the router? I need to try running your code on a web server to try and work out why it's not working as you want it to - any chance you can upload it to a repository I can access?

**Comment by tokidevelop** [comment]
The whole framework can be downloaded at https://ufile.io/af7z2 (its still underconstruction so some functions are not finished or working correctly)
New to github, need to read some more tutorials to understand how to upload / work with github as svn :)

The autoloader method is called in framework/_core/includes/global.php
Hope you can find something. And thanks for helping me out 👍

**Comment by daveh** [comment]
Ok, have got your framework running locally - the URL http://localhost/framework/admin/cms/page (that you mention above) doesn't work, but this one does: http://localhost/admin/cms/page which matches the route - why have you got "framework" as part of your URL when your route doesn't?

**Comment by tokidevelop** [comment]
Framework is not a part of the url, it’s the virtual server name set up from wamp. The urls are like “http://framework/admin/cms/page”

I already got the routing part working without the namespace so I can go further, but if you still want to find why it’s not working, please do. Still ceurius why it’s not working like it should be. 
One more question about the framework that hase nothing to do with routing :p
Why can’t I, if I extend the controller (e.g. in the page controller) not use return? If I use ‘$template = new core\template. Return $template’ doesn’t print out the template, while echo $template does..?

**Comment by daveh** [comment]
But even though it's a virtual server, doesn't the "framework" segment of the URL come through as part of the `$_SERVER['QUERY_STRING']` variable? I always set up virtual hosts using hostnames instead of subfolders, e.g. http://framework.localhost/ - could that be a possibility?

As for returning from the controller, the framework doesn't do anything with the return value from action methods. You could change this if you wanted to, but you don't always want to echo something out from an action method, for example you might want to redirect instead.

**Comment by tokidevelop** [comment]
Hmm need to check it out tonight if it’s possible to change it to a hostname and see it the namespace routing then works. And no, the query string doesn’t print out “framework” segment. How can I change it action methods to use a return? Google isn’t helping me out on this one..

**Comment by daveh** [comment]
The dispatch method in the router calls the controller's action method:

`$oController->$sAction();`

So if you wanted to act on the return value from the action method, you'd do it in there. For example:

`echo $oController->$sAction();`

**Comment by tokidevelop** [comment]
I did made the subdomains, so my urls now look like "http://framework.localhost.beta/admin/cms/page" but still the namespace routing doesnt work.. 
Also, in de route dispatch when i use it like your example `echo $oController->$sAction()` and then in the page controller i use this ` public function indexAction() {
        $oTemplate = new \core\template('home');
        $oTemplate->assign('sTest', 'Sup..');
        return $oTemplate;
    }` the return is still empy, using echo $oTemplate works but thats not how the template class supose to work...

**Comment by daveh** [comment]
When I try that route with your framework (albeit on a different host), I get this response:

`Translation test.Module.Cms.Page.Hello2`

Doesn't that mean it's working?

As for the template, you need to call a method on the template object that returns a string, instead of returning the object itself, for example:

`return $oTemplate->getContents();`

where the `getContents` method returns the contents of the template.

**Comment by tokidevelop** [comment]
Yes then it means it’s working. Strange that I don’t get that? You don’t specify a action with the namespace right? Just route->add(‘admin/cms’, [namespace => module/cms])?

For the template class and the getContent. Isn’t it when i use the magic method __toString with the getContent that it should be automaticly?

**Comment by daveh** [comment]
I haven't changed the code that I downloaded from the link above, I just placed it in a virtual host and accessed it in a browser. So whatever routes are defined in that code work on my machine.

The `__toString` method is used when the object is cast to a string, so you could try this:

`return (string) $oTemplate;`

which will call the `__toString` method (I haven't tried that but that's the general idea)
