### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by aathiraashok804** [daveh/php-mvc#39]
Hai,
How can we add a router with post method..?

**Comment by daveh** [comment]
Hi,

the router doesn't support request-based routes (yet), so you'd have to check the request method using the $_SERVER['REQUEST_METHOD'] value.

**Comment by somkundu1989** [comment]
how to add route  i mean what file has to create in which directory, with which name, and what will be initial declaration and and need get / post example thats all I want.

I was checking the whole its really impressive.
