### ISSUE TITLE
Exception class is not imported

### ISSUE THREAD

**Issue by AramDonyaee** [daveh/php-mvc#4]
Some methods on $exception are not working. Because **Exception** built-in class isn't imported on top of **Core/Error.php** file.

**Comment by daveh** [comment]
Please can you give me an example? I haven't had a problem with the framework throwing exceptions.

**Comment by AramDonyaee** [comment]
You are right, there was a problem in my own environment. Throwing exceptions are working fine now for me. Thank you for your accountability.

**Comment by daveh** [comment]
No problem, glad you got it working. Thank you for letting me know!
