### ISSUE TITLE
question about routing

### ISSUE THREAD

**Issue by alexander340** [daveh/php-mvc#41]
Hello 
I have question 

How I create route like this

https://example.com/watch?v=slug
Instead of example.com/watch/slug

The parameter slug is user define param means it pass value other are part of url how to do this help me

Thanks

**Comment by daveh** [comment]
Hi,

you could do it like this:

`$router->add('watch', ['controller' => 'Watch', 'action' => 'index']);`

The slug parameter in this URL: https://example.com/watch?v=slug is passed in in the query string, and isn't part of the route, so you can access it in the controller like any other query string variable like this:

`$slug = $_GET['slug'];`

**Comment by alexander340** [comment]
Okay thanks
