### ISSUE TITLE
how to make route optional?

### ISSUE THREAD

**Issue by alexander340** [daveh/php-mvc#42]
How to make optional param route like

$router->add('search/{key:[a-z]+}/{category:[a-z]+}',......);

Here I want make catagery option as a optional I don't know how to do this kindly help me 
Like 
example.com/search/Samsung
example.com/search/Samsung/mobiles

Both should be work 
thanks

**Comment by daveh** [comment]
The router doesn't support optional parameters, but one way to do it is to add two routes:

```
$router->add('search/{key:[a-z]+}, ['controller' => 'Search', 'action' => 'show'])
$router->add('search/{key:[a-z]+}/{category:[a-z]+}', , ['controller' => 'Search', 'action' => 'show']);
```

**Comment by alexander340** [comment]
Oh okay so what's plan to add such feature and upload video as well to explain

**Comment by daveh** [comment]
I'm not planning to add optional parameters to the router, but I am working on updating the framework and associated Udemy course that covers how to develop the framework from scratch. I am working on it as much as I can at the moment, but there's no ETA. Hopefully in the next month or two.
