### ISSUE TITLE
No Route matched when try to load css/js from public folder

### ISSUE THREAD

**Issue by LeonBuchner** [daveh/php-mvc#44]
Hey guys,
I tried to load a few css and javascript files from the public folder. I created there two folders: /js and /css

When I now load the page the css and js will not load because the css and js files show "No route matched" as an Exception.

Please help me

**Comment by daveh** [comment]
What URL are you using to load the CSS? If you've changed your web root to the public folder, then you access it directly in that folder, e.g. 

```
<head>
  <link rel="stylesheet" type="text/css" href="/css/theme.css">
</head>
```

Alternatively, it depends on your folder setup and how you're using any .htaccess files. If so, please let me know (e.g. an example of a URL in your site that works)

**Comment by LeonBuchner** [comment]
I have the same folder structure like in your udemy course. I downloaded the new version here from github and started from scratch.

I try to load the stylesheet in my Home View (App->Views->Home->index)

`<link rel="stylesheet" href="../../../public/css/bootstrap.min.css">`

All my css and js is in public/css/bootstrap.min.css and public/js/script.js

When I try to load the css file in my browser I will get the Error: No Route matched

**Comment by LeonBuchner** [comment]
Every Page is working properly but the css and js will not load. When I open the website source code in the browser and click on the css I will get the Exception : No Route matched

**Comment by daveh** [comment]
The view files are rendered by the front controller (via the router class), so any static file will be relative to that, not to the actual view templates themselves. So the CSS for example will be this:

`<link rel="stylesheet" href="/public/css/bootstrap.min.css">`

or this:

`<link rel="stylesheet" href="/css/bootstrap.min.css">`

If neither of those work, please can you give me an example of a URL that works? (e.g. http://localhost/items/index)

**Comment by LeonBuchner** [comment]
`<link rel="stylesheet" href="/css/bootstrap.min.css">`

This works for me! Thank you very much!

**Comment by LeonBuchner** [comment]
Oh wait its just working for the homepage `http://localhost`
When I go to `http://localhost/signup/new` its nor working anymore. No stylesheet will load. No Route matched.

**Comment by LeonBuchner** [comment]
`<link rel="stylesheet" href="/css/bootstrap.min.css">`

This just working for the homepage `http://localhost`
When I go to `http://localhost/signup/new` or any other page its not working anymore. No stylesheet will load. No Route matched.

**Comment by LeonBuchner** [comment]
Thanks its working now!
