### ISSUE TITLE
Getting error $_SERVER['QUERY_STRING'];

### ISSUE THREAD

**Issue by hardzal** [daveh/php-mvc#45]
> Fatal error
> Uncaught exception: 'ErrorException'
> 
> Message: 'Undefined index: QUERY_STRING'
> 
> Stack trace:
> 
> #0 D:\CodeExample\php-mvc\public\index.php(32): Core\Error::errorHandler(8, 'Undefined index...', 'D:\\CodeExample\\...', 32, Array)
> #1 {main}
> Thrown in 'D:\CodeExample\php-mvc\public\index.php' on line 32

How i solve this ?

**Comment by daveh** [comment]
Sometimes the QUERY_STRING element isn't defined in the $_SERVER array - it depends on your web server configuration. Try changing the last line of public/index.php accordingly:

`$router->dispatch(isset($_SERVER['QUERY_STRING']) ?? '');`

**Comment by jhayann** [comment]
hi ? This error occurs when i run the project using
`php -S localhost:8000`

instead of plain 
`$url = $_SERVER['QUERY_STRING']`

i modify it to:
`$url = $_SERVER['SERVER_NAME']=="localhost" ? substr($_SERVER['REQUEST_URI'],1) : $_SERVER['QUERY_STRING'];
`
it works for me ...
