### ISSUE TITLE
RegEx

### ISSUE THREAD

**Issue by kirichain** [daveh/php-mvc#47]
Im not good at RegEx, so can someone explain what do these codes mean ?

`('/\{([a-z]+)\}/', '(?P<\1>[a-z-]+)', `
`('/\{([a-z]+):([^\}]+)\}/', '(?P<\1>\2)',`

may not of all, but i cant understand what exactly `(?P<\1>[a-z-]+) and (?P<\1>\2)` stand for

**Comment by daveh** [comment]
`\1` and `\2` are [backreferences](https://www.regular-expressions.info/backref.html). These are used to refer to a match from the first regular expression in brackets. `?P...` is a [named capture group](https://www.regular-expressions.info/refext.html), which is used to capture part of a string under a certain name.

**Comment by kirichain** [comment]
Thanks for help,

I just begin to MVC and Router, there're so many approaches to learn, in some other Routers, seem they use things like laravel's one, with routes->add('/', function()) or route->get('/', function())

**Comment by daveh** [comment]
With Laravel's and other routers you can assign a closure to a route like that. See also [AltoRouter](https://altorouter.com/) and [FastRoute](https://github.com/nikic/FastRoute).

(I have a full course on developing an MVC framework from scratch, the link is in the description of the repo above.)

**Comment by hoahoctro98** [comment]
about \\/ in `$route = preg_replace('/\//', '\\/', $route);` , does it mean /foo will be foo ? , but if, it should be // or '' ?
