### ISSUE TITLE
Redirecting from one method to another method

### ISSUE THREAD

**Issue by msrumon** [daveh/php-mvc#48]
Hello @daveh, I am using your framework (made some slight changes for my purposes) and what I found is that I am not being able to redirect user from one method to another method (within same class). If I manually type the router associated with that method, it works. But how can I call a method and redirect to the router associated with that method? I have used `call_user_func_array()`, but this only returns the page as response, not redirect to that route.

Views/index.php =>
```
<?php require_once ("inc/header.php"); ?>

    <main class = "container">
      <!--  -->
    </main>

    <script>
      let signinbtn, gauth, guser;

      gapi.load("auth2", () =>
      {
        gapi.auth2.init({client_id: "1038738279308-rp4e2krrrv1c6ljfna51emfmn6ggpjrg.apps.googleusercontent.com", scope: "profile"})
        .then((response) =>
        {
          gauth = response;
          gauth.attachClickHandler(signinbtn, {}, (response) => guser = response, (err) => M.toast({html: `${err.error}`, classes: "rounded amber-text"}));
          if(gauth.isSignedIn.get())
          {
            signinbtn.classList.remove("pulse");
            signinbtn.classList.add("disabled");
            signinbtn.innerHTML = `<i class = "fas fa-spinner fa-pulse fa-fw"></i>`;
            if(!guser) guser = gauth.currentUser.get();
            if(guser)
            {
              fetch("/verify", {method: "POST", headers: {"Content-Type": "text/plain"}, body: guser.getAuthResponse().id_token})
              // .then(() => )
              .catch((err) => M.toast({html: `${err.error}`, classes: "rounded amber-text"}));
            }
          }
        }, (err) => M.toast({html: `${err.error}`, classes: "rounded amber-text"}));

      });

      document.addEventListener("DOMContentLoaded", () =>
      {
        signinbtn = document.querySelector("nav div ul li button");
        signinbtn.onclick = function()
        {
          signinbtn.classList.remove("pulse");
          signinbtn.classList.add("disabled");
          signinbtn.innerHTML = `<i class = "fas fa-spinner fa-pulse fa-fw"></i>`;
        };
      });

      window.addEventListener("load", () =>
      {
        //
      });
    </script>

<?php require_once ("inc/footer.php"); ?>
```

Controllers/Home.php =>
```
<?php

require_once ("../jinis/vendors/gapi/vendor/autoload.php");

class Home extends BaseC
{
  private $oauth, $gclient;

  public function verify ()
  {
    $this->oauth = json_decode (file_get_contents ("../jinis/MVC/Controllers/giveaway_/oauth_credentials.json"));
    $this->gclient = new Google_Client();
    $this->gclient->setAuthConfig ("../jinis/MVC/Controllers/giveaway_/oauth_credentials.json");
    if ($_SERVER["REQUEST_METHOD"] === "POST")
    {
      $body = file_get_contents ("php://input");
      $payload = $this->gclient->verifyIdToken ($body);
      if (($payload["aud"] === $this->oauth->web->client_id) && ($payload["iss"] === "accounts.google.com" || $payload["iss"] === "https://accounts.google.com"))
      {
        $userData = ["id" => $payload["sub"], "email" => $payload["email"], "first_name" => $payload["given_name"], "last_name" => $payload["family_name"], "profile_picture" => $payload["picture"]];
        $args = ["arg" => $userData];
        call_user_func_array ([$this, "dashboard"], $args);
      }
      else return false;
    }
    else header ("location: /");
  }

  public function index ()
  {
    BaseV::render("giveaway_/index.php", ["json" => $this->json, "site" => "Giveaways", "title" => "Home", "asset_dir" => "assets", "style_dir" => "styles", "js_dir" => "scripts"]);
  }

  private function dashboard ($args=null)
  {
    $userDetails = $args;
    BaseV::render("giveaway_/dashboard.php", ["json" => $this->json, "site" => "Giveaways", "title" => "Dashboard", "user" => $userDetails, "asset_dir" => "assets", "style_dir" => "styles", "js_dir" => "scripts"]);
  }
}
```

BaseView.php =>
```
<?php

abstract class BaseV
{
  public static function render (string $filename, array $data = []) : void
  {
    extract ($data, EXTR_SKIP);
    $file = __DIR__ . "/$filename";
    if (is_readable ($file)) require_once ($file);
    else die ("$file NOT found!");
  }
}
```

Let me know if you need additional information.
Thanks in advance.

**Comment by daveh** [comment]
I'm afraid I'm not totally sure what you mean - all action methods in controllers are executed in response to a request that goes via the router. So inside an action method, if you want to redirect to another action method, you have to make another request, using the `location` header as you're doing.

Is that what you meant?

**Comment by msrumon** [comment]
I am sending a request from my `index.php` view to `Home::verify()`. There I am processing the data passed in, outputting some data after processing and sending it back to another route `Home::dashboard()`. Now at `Home::dashboard()` method, I am rendering a view and I WANT TO REDIRECT TO THIS ROUTE. So far, I have managed to get the rendered view as response from `Home::verify()` but can't redirect. Hope I am cleared to you.

**Comment by daveh** [comment]
What happens when you try and redirect from `Home::dashboard()` to `Home::verify()` using a `location` header?

**Comment by msrumon** [comment]
I want the other way around: from `verify()` to `dashboard()`. When I use `location` header, it throws an error from base controller (`Home::dashboard() is private!`). But I don't want it to be public as I don't want user to access this route without logged in.

**Comment by daveh** [comment]
If you want the `dashboard` method to be available in a browser (even if you require the user to be logged in), then it needs to be public. To make sure they're logged in, then you have to check this in the method itself (or in the `before` method in the controller if you're extending the Core\Controller class)

**Comment by msrumon** [comment]
> If you want the `dashboard` method to be available in a browser (even if you require the user to be logged in), then it needs to be public. To make sure they're logged in, then you have to check this in the method itself (or in the `before` method in the controller if you're extending the Core\Controller class)

Alright, these seem getting into me slowly. So, I will make the `dashboard()` method public, check for the user as logged in. And if user is logged in, I will redirect. Will calling the `render()` method redirect to that route in the browser?

**Comment by msrumon** [comment]
> If you want the `dashboard` method to be available in a browser (even if you require the user to be logged in), then it needs to be public. To make sure they're logged in, then you have to check this in the method itself (or in the `before` method in the controller if you're extending the Core\Controller class)

Nah, it's not working as you suggested. I am manually calling the `dashboard()` method with `call_user_func_array()` function, I have not implemented the `before()` method because it creates some conflicts with other classes. I changed the `Home` class like the following:
```
<?php

require_once ("../jinis/vendors/gapi/vendor/autoload.php");

class Home extends BaseC
{
  private $oauth, $gclient;

  public function verify ()
  {
    $this->oauth = json_decode (file_get_contents ("../jinis/MVC/Controllers/giveaway_/oauth_credentials.json"));
    $this->gclient = new Google_Client();
    $this->gclient->setAuthConfig ("../jinis/MVC/Controllers/giveaway_/oauth_credentials.json");
    if ($_SERVER["REQUEST_METHOD"] === "POST")
    {
      $body = file_get_contents ("php://input");
      $payload = $this->gclient->verifyIdToken ($body);
      if (($payload["aud"] === $this->oauth->web->client_id) && ($payload["iss"] === "accounts.google.com" || $payload["iss"] === "https://accounts.google.com"))
      {
        $userData = ["id" => $payload["sub"], "email" => $payload["email"], "first_name" => $payload["given_name"], "last_name" => $payload["family_name"], "profile_picture" => $payload["picture"]];
        $args = ["arg" => $userData];
        call_user_func_array ([$this, "dashboard"], $args);
      }
      else return false;
    }
    else header ("Location: /");
  }

  public function index ()
  {
    BaseV::render("giveaway_/index.php", ["json" => $this->json, "site" => "Giveaways", "title" => "Home", "asset_dir" => "assets", "style_dir" => "styles", "js_dir" => "scripts"]);
  }

  public function dashboard (array $args = [])
  {
    if($args)
    {
      $userDetails = $args;
      BaseV::render("giveaway_/dashboard.php", ["json" => $this->json, "site" => "Giveaways", "title" => "Dashboard", "user" => $userDetails, "asset_dir" => "assets", "style_dir" => "styles", "js_dir" => "scripts"]);
    }
    else header ("Location: /");
  }
}
```
And now inside the `dashboard()` method, always the else statement is being executed, although I am passing values from `verify()` method, even if I am logged in and trying to manually load the `dashboard` route.

**Comment by daveh** [comment]
To render a view (i.e. send something to the client), you have to call the `render` method as you're doing. If you want to redirect to another action, you need to use the location header. You can't really call one action method from another using `call_user_func_array` - instead, if you want to show the dashboard at that point, you need to redirect to it:

```
// call_user_func_array ([$this, "dashboard"], $args);

header ("Location: /dashboard");
```

**Comment by msrumon** [comment]
Alright. Seems my confusions have been cleared. Thanks. You're the BEST! 🥰
