### ISSUE TITLE
Passing Variables

### ISSUE THREAD

**Issue by NicolJamie** [daveh/php-mvc#5]
I cannot seem to pass more than one digit at a time, example: /home/11 returns an error when /home/1 works. I also can only pass a single letter, example: /home/a works fine whilst /home/abc returns an error.

**Comment by NicolJamie** [comment]
Managed to solve this by changing the dispatch to use: ltrim($_SERVER['REQUEST_URI'], '/') and the regex to be {id:\w+}

**Comment by daveh** [comment]
The regex was probably missing the "+".

`\w` = one "word" character - letters, numbers, underscore etc.

So to make it one or more characters, you need to add the "+": `\w+`

However, if your IDs are only going to be numeric, I would recommend changing it to use `\d`, as this is just number characters. So the variable in your route would be `{id:\d+}`.

As for removing the leading slash, I've tested the router with Apache and nginx, and it works without your added `ltrim` code - which web server are you using? Just so I can test it to see if it works differently.

**Comment by NicolJamie** [comment]
Yes, was missing the "+" at the end. Works perfectly now.
