### ISSUE TITLE
css file included

### ISSUE THREAD

**Issue by kirichain** [daveh/php-mvc#50]
For you MVC structure, how css file should be included ?
I use 
`<link rel="stylesheet" href="/css/main.css">`
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">` 
in index.html, the css file makes red color for h1 tag, but there is nothing when page loaded , i tried http://localhost/css/main,css but theres nothing too, so what i missed ?

**Comment by daveh** [comment]
If you've changed the document root of the web server to be the public folder of the framework, and you have a file public/css/main.css, then the URL of that file will be http://localhost/css/main.css.

It depends if you're running the framework in a subfolder of the web root or in the root or not. What is the URL of your homepage?

**Comment by valeriot30** [comment]
@daveh The problem is that your code doesn't exclude assets folder (like stylesheets and images) that are noticed as potential routes

**Comment by daveh** [comment]
@KaostDev [the .htaccess folder](https://github.com/daveh/php-mvc/blob/master/public/.htaccess) in the public folder does exclude files, directories and links:

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
```
which works if the web root has been set to the public folder. If not, then another .htaccess folder is required. Do you have a recommendation for doing it another way?
