### ISSUE TITLE
How to create a subnavigation menu

### ISSUE THREAD

**Issue by MalithSena** [daveh/php-mvc#51]
I'm trying to create a dropdown subnavigation menu under the main navigation called "Destinations". Under destinations, there will be few "Cities" added. So how to route the Destinations menu to its subnav cities like in below example?  
Destinations 
-> Sydney
-> Paris

**Comment by daveh** [comment]
The menu links would map to a route that contained a variable for the cities. You could do this with an ID for the cities, for example
```
example.com/destinations/12
example.com/destinations/34
```
where the IDs would be of cities in the database. Alternatively, you could map directly to city names, like this:
```
example.com/destinations/sydney
example.com/destinations/paris
```
which you could do with a route like this:

`
$router->add('destinations/{city:\w+}', ['controller' => 'Destination', 'action' => 'show');
`

then in the `showAction` method in the Destination controller you could access the city in the `route_params` property:

```
public function showAction()
{
     $city = $this->route_params['city'];
}
```

Is that what you meant?

**Comment by MalithSena** [comment]
It's exactly what I meant. Thanks...
