### ISSUE TITLE
Default /index route

### ISSUE THREAD

**Issue by Dripnix** [daveh/php-mvc#54]
Hello,

nice work on the MVC framework.
Everything is running smoothly but there is an issue on routing, for example I created the controller Application but when travelling by link < _a href="Application/"> it doens't resolve to the default action Index. Thus every controller action has to be passed as Application/Index... how can I solve this so that it is automatic for /Index (but has to be defined for other stuff like Application/GetCustomers) ?

Thank you!

**Comment by daveh** [comment]
There are two ways you can solve this - one is to add a route that includes a default action, e.g.

```
$router->add('{controller}/{action}');
$router->add('{controller}', ['action' => 'index']);
```
The other is to modify the router (Core\Router.php) to include a default action when there isn't one in the matched route - for example in the dispatch method:

replace this line:
`$action = $this->params['action'];
`

with this:
`$action = $this->params['action'] ?? 'index';
`

Is that what you meant?

**Comment by Dripnix** [comment]
I've tried it and is working great, thank you. 
Already had tried it before but forgot the braces in action.
Thank you again.
