### ISSUE TITLE
before() method not working...

### ISSUE THREAD

**Issue by badalyan** [daveh/php-mvc#55]
Hi, I'm having trouble getting the `before()` method to work. Below is my code:

```
<?php

namespace App\Controllers;

use \Core\View;

class Dashboard extends \Core\Controller
{
    protected function before()
    {
        echo "hello world";
        return false;
    }

    public function homepage()
    {
        // shows homepage
    }
}
```

When I run this code, the homepage still displays and the "hello world" text never appears. Am I missing something?

**Comment by daveh** [comment]
Hi,

you need to suffix your action methods names with "Action":

`public function homepageAction()`

(I haven't added this to the documentation yet as I'm currently rewriting the framework so that you don't have to do this!)

**Comment by vince844** [comment]
Hi Daveh I’ve followed your course on Udemy and really appreciated your help. Do you know when the new version of the framework will be released? Will it be updated on Udemy and will it be easy to upgrade from the current framework? Thanks for your work

**Comment by badalyan** [comment]
> Hi,
> 
> you need to suffix your action methods names with "Action":
> 
> `public function homepageAction()`
> 
> (I haven't added this to the documentation yet as I'm currently rewriting the framework so that you don't have to do this!)

@daveh I noticed that without this suffix, most everything still works properly. Is this suffix only a requirement for the before & after filters?

**Comment by daveh** [comment]
@vince844 I don't have a date I'm afraid, but I'm working on it as much as I can! It's an update to both the framework and the Udemy course, and there will be an upgrade guide from the current version to the new one.

@badalyan Yes, the suffix is only needed for the before and after filters to work (it's a consequence of how this works by using the `__call` method)

**Comment by badalyan** [comment]
@daveh thanks — it worked!
