### ISSUE TITLE
not config in nginx route not work

### ISSUE THREAD

**Issue by milladka** [daveh/php-mvc#57]
# **nginx configuration** to remove the question mark from the URL but maintain the query string
`
location / { 
    if (!-f $request_filename){
        set $rule_0 1$rule_0;
    }   
    if (!-d $request_filename){
        set $rule_0 2$rule_0;
    }
    if ($rule_0 = "21"){
        rewrite ^/(.*)$ /index.php?$1 last;
    }   
}
`
just work route home / index

other route not work in **Nginx**

**Comment by daveh** [comment]
Please can you give me an example of a route (URL) that _doesn't_ work, and what exactly do you see in the browser when it happens?

**Comment by milladka** [comment]
all the time, It only shows the main route, 'home / index'.
But I don't know exactly how to configure this project in nginx.
Should we put a config file in the project root folder?
Or should we put a file in the public folder?

For example, for apache, the htaccess file must be in the root folder and the public folder.
I know the nginx.conf file needs to be changed. Do I need to add a config file to a part of the project?

**Comment by daveh** [comment]
No, you can do it in the nginx.conf file itself, e.g.

```
location / { 
    if (!-f $request_filename){
        set $rule_0 1$rule_0;
    }   
    if (!-d $request_filename){
        set $rule_0 2$rule_0;
    }
    if ($rule_0 = "21"){
        rewrite ^/(.*)$ /index.php?$1 last;
    }   
}
```
What exactly are the URLs that you're trying? Also, are you running the framework in a subfolder or the web root?

**Comment by milladka** [comment]
for example add route home/about , but it only shows the index.

in the root

**Comment by daveh** [comment]
Please can you let me know the exact URL you're putting in the browser's address bar, e.g. http://localhost/home/about ?

**Comment by milladka** [comment]
yes http://localhost/home/about

**Comment by milladka** [comment]
thank @daveh 🌿

```
location / { 
    if (!-f $request_filename){
        set $rule_0 1$rule_0;
    }   
    if (!-d $request_filename){
        set $rule_0 2$rule_0;
    }
    if ($rule_0 = "21"){
        rewrite ^/(.*)$ /index.php?$1 last;
    }   
}
```

and project in root.
its worked.
