### ISSUE TITLE
Fatal error: Class 'Twig_Loader_Filesystem' not found in ...

### ISSUE THREAD

**Issue by RoyBradley** [daveh/php-mvc#6]
Download the framework, made no changes, just ran what was already there. I got the following error:
`
```
Fatal error: Class 'Twig_Loader_Filesystem' not found in ...\MVC\Core\View.php on line 47
Call Stack
#    Time    Memory    Function                                                Location    
1    0.0021    141888  {main}( )                                               ...\index.php:0
2    0.0225    219288  Core\Router->dispatch( )                                ...\index.php:31
3    0.0282    228048  index ( )                                               ...\Router.php:121
4    0.0282    228208  Core\Controller->__call( )                              ...\Router.php:121
5    0.0282    228512  call_user_func_array:{...\Core\Controller.php:48} ( )   ...\Controller.php:48
6    0.0282    228624  App\Controllers\Home->indexAction( )                    ...\Controller.php:48
7    0.0306    234256  Core\View::renderTemplate( )                            ...\Home.php:22

````
roy.bradley@fusiion.com

**Comment by daveh** [comment]
Hi Roy, have you installed the [Twig](http://twig.sensiolabs.org/) framework? It isn't included in the framework, it needs to be installed separately. First you need Composer (installation instructions [here](https://getcomposer.org/doc/00-intro.md) if you need them), then once you have that, go to the folder where you've installed the framework on the command line (where the composer.json file is) and run this command: `composer update`. This will install Twig, and that error will disappear.

Please let me know if you have any problems.

**Comment by RoyBradley** [comment]
Sorry, I read the readme file but read the notes in the table.

Thank you
Roy
