### ISSUE TITLE
Passing parameters with POST Ajax

### ISSUE THREAD

**Issue by MincDev** [daveh/php-mvc#62]
Hi, thanks for this awesome MVC template. I am only struggling with one simple thing; passing parameters through POST using ajax. Could you advise how I need to setup my routes to allow for this?

**Comment by daveh** [comment]
If you send values using POST, you can access them in the `$_POST` array as normal. This is true for regular forms and data submitted via Ajax. You don't need to do anything with the routes, these don't affect POST data.

**Comment by MincDev** [comment]
Ah, I see. 

Seems I tried overcomplicating it as a result of using frameworks where you do stuff like $this->getRequest()->getParsedBody();

Lol, thanks!

**Comment by daveh** [comment]
A lot of frameworks do do that, mainly for testing purposes and to keep things nicely encapsulated (superglobals like `$_POST` are generally frowned upon). For this version of the framework though I kept it simple :-)
