### ISSUE TITLE
Uncaught Error: Call to a member function prepare() on null

### ISSUE THREAD

**Issue by TDA-KH** [daveh/php-mvc#63]
Notice: Undefined property: Food::$database in C:\xampp\htdocs\mysite\models\food.php on line 32

$query = $this->database->prepare("SELECT id, name, type, price, active FROM `food`");

**Comment by daveh** [comment]
This error means the database property of the current object (`$this`) is null. You need to set that property to something somewhere.

**Comment by kishevans** [comment]
Hi daveh, i have the same isuue.

Error logs
Uncaught exception: 'Error' with message 'Call to a member function prepare() on null'
Stack trace: #0 C:\xampp\htdocs\MVC + Login system\App\Controllers\Signup.php(35): App\Models\User->save()
#1 [internal function]: App\Controllers\Signup->createAction()
#2 C:\xampp\htdocs\MVC + Login system\Core\Controller.php(51): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\MVC + Login system\Core\Router.php(142): Core\Controller->__call('create', Array)
#4 C:\xampp\htdocs\MVC + Login system\Public\index.php(59): Core\Router->dispatch('signup/create')
#5 {main}
Thrown in 'C:\xampp\htdocs\MVC + Login system\App\Models\User.php' on line 53

![User Php](https://user-images.githubusercontent.com/19976633/94670579-6cd79480-031b-11eb-828a-ec018078670e.PNG)

The prepare statement is also used in email checking below

![User Php email exists](https://user-images.githubusercontent.com/19976633/94671603-c3919e00-031c-11eb-8fb3-423a27da4c52.PNG)

How could prepare() be null when a parameter is clearly being passed?

**Comment by daveh** [comment]
Hi @kishevans  - that error means the `prepare` method is being called on a variable that contains null. The variable is `$db`. This line is setting that value:

$db = static::getDB();`
`

So the `getDB` method is returning null. Please check that method to make sure it's returning a database instance (post it here if necessary)

**Comment by kishevans** [comment]
The getDb() method is implemented as below

![Model php getDB()](https://user-images.githubusercontent.com/19976633/94735020-c1f2c500-0372-11eb-812f-1056f63790ad.PNG)

**Comment by MincDev** [comment]
@kishevans Have you set those Config variables in the config file?

**Comment by daveh** [comment]
@kishevans The `return $db;` line is in the wrong place - if you call the method more than once in the same request, it will return null - it needs to be the last line of the method:

```
protected static function getDB()
{
    ...

    return $db;
}
```

**Comment by kishevans** [comment]
Thank you @daveh  placing the return $db statement at the end of the function solved it.

**Comment by aashutosh2820** [comment]
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
Warning: Undefined array key "db" in /home/u698064296/domains/sarkarijobdikha.com/public_html/counter.php on line 6

Fatal error: Uncaught Error: Call to a member function prepare() on null in /public_html/counter.php:6 Stack trace: #0 /public_html/counter.php(17): checkPageName() #1 /public_html/single.php(45): updateCounter() #2 {main} thrown in /public_html/counter.php on line 6****


Any solution

**Comment by daveh** [comment]
@aashutosh2820 The "root" account doesn't have access to the database with the password you're using (blank it looks like). Try creating a new user or finding out the root password.

**Comment by aashutosh2820** [comment]
Thanks  Alot  Dave

**Comment by Iranks20** [comment]
Attatched below are my codes where i think my error may be coming from
![Screenshot (54)](https://user-images.githubusercontent.com/104513917/215317352-9a5d89e4-230d-4086-b72b-9e5c5f850c31.png)
![Screenshot (56)](https://user-images.githubusercontent.com/104513917/215318194-5be38cc8-b09f-410f-a806-24c7546a04f0.png)

Hi Daveh i have an issue in running php crud endpoints hope you help me out
Database could not be connected: could not find driver<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function prepare() on null in E:\php-rest-api\class\employees.php: 21
Stack trace:
#0 E:\php-rest-api\api\read.php(10): Employee-&gt;getEmployees()
#1 {main
  thrown in <b>E:\php-rest-api\class\employees.php</b> on line <b>21</b><br />

**Comment by daveh** [comment]
@Iranks20 This means the database driver you're trying to use isn't installed / enabled - have a look at [this answer](https://stackoverflow.com/a/50592271/185553) to see if it helps.

**Comment by Iranks20** [comment]
It doesn't work for me ..... i think the error is in my codes may be because eventhough i turnoff my xamp and i run the codes i still receive the same error yet i expected to  see something showing that the server is off

**Comment by daveh** [comment]
@Iranks20 Is your database server (MySQL in XAMPP) starting correctly, or is there an error message?

**Comment by Bobdaves-max** [comment]
Hello Dave! Me too I get this message
Fatal error: Uncaught Error: Call to a member function prepare() on null in /data/data/com.termux/files/home/Ecommerce Site PHP/ecommerce/index.php:56 Stack trace: #0 {main} thrown in /data/data/com.termux/files/home/Ecommerce Site PHP/ecommerce/index.php on line 56



```

 <h2>Monthly Top Sellers</h2>
		       		<?php
		       			$month = date('m');
		       			$conn = $pdo->open();

		       			try{
		       			 	$inc = 3;	
				👉    $stmt =$conn ->prepare();
						    ("SELECT *, SUM(quantity) AS total_qty FROM details LEFT JOIN sales ON sales.id=details.sales_id LEFT JOIN products ON products.id=details.product_id WHERE MONTH(sales_date) = '$month' GROUP BY detai.....................

**Comment by daveh** [comment]
That error means `$conn` contains null - which probably means it hasn't connected properly, more than likely due to incorrect database credentials (username, password etc.)
