### ISSUE TITLE
Css and JS problem

### ISSUE THREAD

**Issue by GuiHSilva** [daveh/php-mvc#65]
A are linking my css and js files with this method in the base.html
`<link rel="stylesheet" href="assets/plugins/fontawesome-free/css/all.min.css">`
and the directory of this file is /plublic/assets/plugins/fontawesome...... ok, its work normal in the home url (http://localhost/mvc/public/)

but when i try access the url http://localhost/test/public3/person , not works (404 to find the file in http://localhost/test/public3/person/assets/plugins/fontawesome , (wrong!) )

**Comment by daveh** [comment]
You need to start the href attribute (the URL) with a slash, so it's relative to the root of the site. Otherwise it's relative to the current page, which is why it works on the homepage but not on other pages:

`<link rel="stylesheet" href="/assets/plugins/fontawesome-free/css/all.min.css">`

**Comment by GuiHSilva** [comment]
I'm sorry for the two issues, I didn't see that I had already created one

the problem has been fixed, thank you very much
