### ISSUE TITLE
Css and JS problem

### ISSUE THREAD

**Issue by GuiHSilva** [daveh/php-mvc#66]
A are linking my css and js files with this method in the base.html
`<link rel="stylesheet" href="assets/plugins/fontawesome-free/css/all.min.css">`
and the directory of this file is /plublic/assets/plugins/fontawesome...... ok, its work normal in the home url (http://localhost/mvc/public/)

but when i try access the url http://localhost/test/public/person , not works (404 to find the file in http://localhost/test/public/person/assets/plugins/fontawesome , (wrong!) )

**Comment by GuiHSilva** [comment]
I believe my explanation has become difficult to understand, so here is a link shown what happens: https://youtu.be/5h8kT7Nh3Bk

**Comment by daveh** [comment]
Thank you for the explanation video - I replied to this on the other issue you opened [here](https://github.com/daveh/php-mvc/issues/65#issuecomment-683077486).
