### ISSUE TITLE
php code don't works inside views

### ISSUE THREAD

**Issue by CienZZZ** [daveh/php-mvc#67]
Hello, something like this:
`{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}

    <h1>Welcome in home:)</h1>
    <h1><?php echo'php render works ?' ?></h1>

{% endblock %}`

render only:
Welcome in home:)

looks like php code isn't run in views ?

**Comment by daveh** [comment]
You can't use PHP code inside a Twig template. You have to use only Twig commands. If you want some custom PHP code, you have to put it in a Twig extension and call that from your Twig code. More details on Twig extensions [here](https://symfony.com/doc/current/templating/twig_extension.html).

**Comment by telemoes** [comment]
Note do not make for everything a TWIG command you can beter render it in PHP put in a array and print in twig is much faster then make serval commands in TWIG.

**Comment by CienZZZ** [comment]
Ok, thanks for help
