### ISSUE TITLE
Routing with subdomain

### ISSUE THREAD

**Issue by pagodzik** [daveh/php-mvc#76]
Hi

 Structure on the server:
 /var/www/html/MyApp/public/

 domain.com/MyApp/public/ works well
but domain.com/MyApp/ give 500 error

/var/www/html/MyApp/.htaccess is:
RewriteEngine On
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) public/$1 [L]

/var/www/html/MyApp/public/.htaccess is:
RewriteEngine On
RewriteBase /MyApp

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^(.*)$ index.php?$1 [L,QSA]

index.php has
$router->add('/', ['controller' => 'Home', 'action' => 'index']);

What I did wrong?

**Comment by daveh** [comment]
If you're getting a 500 error, the details of that error will be in the web server's error log - what does that say?

**Comment by pagodzik** [comment]
> If you're getting a 500 error, the details of that error will be in the web server's error log - what does that say?

It says nothing...

But I found that rule RewriteRule (.*) public/$1 [L] change url to "public/MyApp/" instead of "MyApp/public".

So I've changed htaccess rules for this and it works now:
RewriteRule ^(.*)$ http://%{HTTP_HOST}/MyApp/public/$1 [L]
