### ISSUE TITLE
preg_replace not working properly?

### ISSUE THREAD

**Issue by diablo-rift-simulator** [daveh/php-mvc#8]
Greetings, Dave!
I'm having an issue with
`$route = '{controller}/{action}';`
`$route = preg_replace('/\//', '\\/', $route);`
`// Convert variables e.g. {controller}`
`$route = preg_replace('/\{([a-z]+)\}/', '(?P<\1>[a-z-]+)', $route);`
`// Convert variables with custom regular expressions e.g. {id:\d+}`
`$route = preg_replace('/\{([a-z]+):([^\}]+)\}/', '(?P<\1>\2)', $route);`
`// Add start and end delimiters, and case insensitive flag`
`$route = '/^' . $route . '$/i';`
`echo $route;`
my output is:
`/^(?P[a-z-]+)\/(?P[a-z-]+)$/i`
however, in your tutorial it says that output should be different, my output doesn't insert names of backreferences...
thanks for your attention:)

**Comment by daveh** [comment]
Hi Dmitry,

it took me a while to figure this one out - it _is_ actually working, but what's happening is you're printing the processed route out to the browser using this code:

`echo $route;`

The route that it's printing is this:

`/^(?P<controller>[a-z-]+)\/(?P<action>[a-z-]+)$/i`

but what's happening is the browser thinks that `<controller>` and `<action>` are HTML tags, so it tries to process them, and in doing so removes them. To see the actual route, you can either use the [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php) function:

`echo htmlspecialchars($route);`

or simply view the source of the page.

I hope that helps!

Cheers,
Dave

**Comment by diablo-rift-simulator** [comment]
Wow, THANKS, Dave! I was so frustrated and couldn't find any answer on the internet...
You are my savior, thanks for helping me out, you are the best teacher ever!!!
