### ISSUE TITLE
Form action with Error 404

### ISSUE THREAD

**Issue by salvatorericcardi** [daveh/php-mvc#81]
Hi, I'm with IIS 10, installed on Windows 10, and I inserted the 

`action='login'` 

into an html form and the code below into /App/Controllers/Home.php:

`public function loginAction()
    {
        echo 'ciao';
    }`

Echo 'ciao' is only a test... but my problem is that the form return Error 404 every time. I tried to insert 

`$router->add('login', ['controller' => 'Home', 'action' => 'login']);` 

into index.php in public folder but every time the same error.

Can you help me please? Thank you very much.

**Comment by daveh** [comment]
What URL are you using that gives you the error? It could be that you don't have URL rewriting enabled - for example, if this URL doesn't work: http://localhost/login (or whatever hostname you're using) but this one does: http://localhost/index.php?login then that's the problem. If so, this IIS configuration should work:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <directoryBrowse enabled="false" />
    <rewrite>
      <rules>
        <rule name="rule 1p" stopProcessing="true">
          <match url="^(.+)/$"/>
          <action type="Rewrite" url="/{R:1}"/>
        </rule>
        <rule name="rule 2p" stopProcessing="true">
          <match url="^(.*)$"/>
          <action type="Rewrite" url="/index.php?{R:1}" appendQueryString="true"/>
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by salvatorericcardi** [comment]
The problem is that there is a subfolder called **online_examination**. This is the path: **localhost/online_examination/...** I have no idea how to use the regex in the rewrite rules, this is my limit. If you can explain me I appreciate, otherwise I don't know.

Anyway I will give you the list of the URLs that are working on my code without your rewrite rules:
**localhost/online_examination/public** works
**localhost/online_examination/public/login** where login is the form action and the action in the controllers folder not works

Instead with the rules the first URL I listed gives me the Error "this page doesn't redirect in the correct way" and the web.config file is in the **localhost root** not in **localhost/online_examination**.

**Comment by daveh** [comment]
I'm afraid I'm not that familiar with IIS configuration, but I would try including the subfolder in the rewrite rules, for example:

`<action type="Rewrite" url="online_examination/index.php?{R:1}" appendQueryString="true"/>`

**Comment by VladaBG1** [comment]
You can stop IIS with PowerShell.


Run PowerShell as administrator and type the next command.


Get-WindowsOptionalFeature -online | ? featurename -like "IIS" | Disable-WindowsOptionalFeature -Online -Remove

**Comment by salvatorericcardi** [comment]
I tried to migrate to nginx, but I see Error 403 (forbidden) in **localhost/php-mvc** that's the root and below the nginx.conf file:

`http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

	#autoindex on;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   "C:\inetpub\wwwroot";
            index  index.html index.htm index.php;

	    if (!-f $request_filename){
            	set $rule_0 1$rule_0;
    	    }   
    	    if (!-d $request_filename){
            	set $rule_0 2$rule_0;
    	    }
    	    if ($rule_0 = "21"){
	    	rewrite ^/(.*)$ /index.php?$1 last;
    	    }   
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
}`

Have you idea why does it show the Error 403?

**Comment by daveh** [comment]
403 is a permissions problem - is there any more detail in the web server's error log?

**Comment by salvatorericcardi** [comment]
Hi, sorry I only understood now how the code works. Thank you for your time, it was my fault.
