### ISSUE TITLE
How can i instance a Model method in a Controller ?

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#82]
**Fatal error**
Uncaught exception: 'Exception'

Message: 'Method getAllAction not found in controller App\Controllers\User'

thats my controller : 

`<?php

namespace App\Controllers;

use \Core\View;

/**
 * Home controller
 *
 * PHP version 7.0
 */
class User extends \Core\Controller
{

    /**
     * Show the index page
     *
     * @return void
     */
    public function indexAction()
    {
				
				$users = User::getAll();
        View::renderTemplate('User/users.twig', array('users' => $users));
    }
}`

**Comment by daveh** [comment]
You need to reference the User model class in its own namespace - so this:

`$users = \App\Models\User::getAll();`

**or** add a `use` statement at the top to import it into the current namespace:

`use App\Models\User;`

**Comment by roobiniano** [comment]
> You need to reference the User model class in its own namespace - so this:
> 
> `$users = \App\Models\User::getAll();`
> 
> **or** add a `use` statement at the top to import it into the current namespace:
> 
> `use App\Models\User;`

🤦‍♂️, thanks works perfectly, sorry, it was late when i was working
the framwork is beatiful !
