### ISSUE TITLE
How to insert data into the DB from the View

### ISSUE THREAD

**Issue by CherukuriSiva** [daveh/php-mvc#84]
Hi,

First of all, thank you for open sourcing this wonderful library. I have followed both of your Udemy tutorials.

![image](https://user-images.githubusercontent.com/6113750/111247341-408da700-8621-11eb-9f65-19b862bf6ccc.png)

After successful login, I am taking the User to the Home Page. 
On my home page, 

1. Users can enter some data in the input text field.
2. They click "Place Bet" button.
3. Data will be updated in the DB tables.
4. I want to stay in the same and I do not want to reload the page. 

From the View page... how can I invoke a function which is written inside a controller. I tried to use

`<a href="/test/test">Test/a>`
and `<form action="/test/test" method="post">` but browser is redirecting to new page. All I want to do is just update the data in the DB and stay at same page. I don't even want to reload the page. 

I have created a controller
` *
 * PHP version 7.0
 */
class Test extends \Core\Controller
{

    /**
     * Show the signup page
     *
     * @return void
     */
    public function testAction()
    {
       //updateDB 
      //code
    }

}`

I am facing difficulties to achieve the above functionality. Maybe I have not understood the library.

**Comment by CherukuriSiva** [comment]
Do I need to use POST AJAX requests? 
If yes Do I need to create a separate PHP file for this AJAX request without following the MVC pattern...?

**Comment by daveh** [comment]
I just replied to your question inside the Q&A section on the course, but yes, you need to use an Ajax request. You can send these using post, getting the data from the form, for example [like this](https://www.devextent.com/fetch-api-post-formdata-object/).
