### ISSUE TITLE
PDO and PostgreSQL

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#87]
Hi Dave, I wanted to ask you about using postgreSQL as a database engine, I am starting a new project that uses that engine, and I was thinking of using your framework for it.
thank you very much, greetings

**Comment by daveh** [comment]
If you use PDO, you can connect to PostgreSQL just like MySQL, you just need a different data source name. Useful resources are [here](https://www.phptutorial.net/php-pdo/pdo-connecting-to-postgresql/) and [here](https://www.php.net/manual/en/ref.pdo-pgsql.php).

**Comment by roobiniano** [comment]
> If you use PDO, you can connect to PostgreSQL just like MySQL, you just need a different data source name. Useful resources are [here](https://www.phptutorial.net/php-pdo/pdo-connecting-to-postgresql/) and [here](https://www.php.net/manual/en/ref.pdo-pgsql.php).

thanks !
