### ISSUE TITLE
response object

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#88]
Hi Dave, again with a question.

Exist in the framework some object or method to handle the responses of the controllers.

Something like this:

`
$ response->withJson(array($status = 404, $message = "Not found"));
`

thanks again !

**Comment by daveh** [comment]
Not at the moment, each action method has to deal with the response directly. So in this case you'd have to do this:

```
http_response_code(404);
header('Content-Type: application/json');
echo json_encode(['message' => 'Not found']);

```

A future version of the framework will have response objects, but I don't have an ETA for when that will be ready.

**Comment by roobiniano** [comment]
> Not at the moment, each action method has to deal with the response directly. So in this case you'd have to do this:
> 
> ```
> http_response_code(404);
> header('Content-Type: application/json');
> echo json_encode(['message' => 'Not found']);
> ```
> 
> A future version of the framework will have response objects, but I don't have an ETA for when that will be ready.

maybe add some response methods (json, text / html) in Core/Controller to handle this for now, is it good practice?

**Comment by daveh** [comment]
That's a good idea, yes.
