### ISSUE TITLE
error in router

### ISSUE THREAD

**Issue by othmanekahtal** [daveh/php-mvc#89]
Fatal error
Uncaught exception: 'Exception'

Message: 'Method newAction not found in controller App\Controllers\signup'

Stack trace:

#0 C:\Users\admin\Desktop\php-mvc\Core\Router.php(121): Core\Controller->__call('new', Array)
#1 C:\Users\admin\Desktop\php-mvc\public\index.php(32): Core\Router->dispatch('signup/new')
#2 {main}
Thrown in 'C:\Users\admin\Desktop\php-mvc\Core\Controller.php' on line 52
what is the issue here ?

**Comment by daveh** [comment]
Do you have a method called newAction in your signup controller?

**Comment by othmanekahtal** [comment]
I forgot it , Problem fixed thank you soo much devah😄
