### ISSUE TITLE
Named routes?

### ISSUE THREAD

**Issue by joemottershaw** [daveh/php-mvc#9]
Over the last year I've been using Laravel which has the ability to name routes when declaring them, then using those named routes in the view files as links rather than hard-coding the link into the view file for example `<a href="{!! route('name.of.route') !!}">Link</a>`.

I know this framework is used in a Udemy course so it would mean updating the videos in the course too I guess, but is this something that you think you would add or could easily be added?

**Comment by daveh** [comment]
Hi Joe,

thank you for your interest in my framework! That's a good idea. I'm actually working on an updated version of the course at the moment, so if it fits in with what I'm teaching on the course, I'll certainly add it.

It shouldn't be too complicated to add something like this - I suppose it would be adding the name to the array of routes in the router, then making this available in a helper in the view templates. I'll look into it when I get to the section on Twig and let you know.

Thank you for the suggestion!

Best wishes,
Dave
