### ISSUE TITLE
ajax request 404 not found

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#91]
Hi Dave, how are you? Here again with questions.

I am running the application on a windows server.
The root of the server is pointed to the public folder of the project. 
The rewrite rule go to index.php, but QUERY_STRING is always empty.

thats my rewrite in IIS, i cant get de routes in QUERY_STRING

```
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <defaultDocument>
      <files>
        <clear />
        <add value="index.php" />
      </files>
    </defaultDocument>
    <rewrite>
      <rules>
        <rule name="Imported Rule 2" stopProcessing="true">
          <match url="^(.*)$" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
            <add input="{URL}" pattern="^/favicon.ico$" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.php?q={R:1}" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

Thanks  again dave

**Comment by raleandri** [comment]
I think I found a way that the rewrite always reaches the index.php but it is not matching any route.

**Comment by raleandri** [comment]
> Hi Dave, how are you? Here again with questions.
> 
> I am running the application on a windows server (http://sd-1965379-w.ferozo.com/)
> 
> The root of the server is pointed to the public folder of the project.
> 
> So far everything works fine, but when I try to do an ajax to a declared route (ej: http://sd-1965379-w.ferozo.com/login) the server returns 404 because it is trying to access that /login directory
> 
> Can you think that could be what happens?
> 
> As always, thank you very much for your time and your wisdom.
> 
> Greetings

I already have the rewrite in IIS to get to the index.php always, but $ _SERVER ['QUERY_STRING'] is always empty.

**Comment by raleandri** [comment]
> $ _SERVER ['QUERY_STRING']

thats my rewrite in IIS, i cant get de routes in QUERY_STRING

```
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <defaultDocument>
      <files>
        <clear />
        <add value="index.php" />
      </files>
    </defaultDocument>
    <rewrite>
      <rules>
        <rule name="Imported Rule 2" stopProcessing="true">
          <match url="^(.*)$" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
            <add input="{URL}" pattern="^/favicon.ico$" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.php?q={R:1}" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by roobiniano** [comment]
Solve, just a litlle modification ja
`
<action type="Rewrite" url="index.php?{R:1}" appendQueryString="true" />`
