### ISSUE TITLE
twig include error

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#93]
Hi Dave, how are you?

I am trying to include some templates (eg header) in my base.html but it is giving me a fatal error (template not found).
The paths are ok and the file names too. I tried with the .html and .twig extensions but it gives the same error.

Is there something I need to keep in mind?

example code:

```
<body>
        {% include 'template-parts/header.html' %}

        {% block body %}{% endblock %}
</body>
```

thanks again

**Comment by daveh** [comment]
`include` is based on the path to the views folder, so the above line will look for the file views/template-parts/header.html - is that where the file is located?

**Comment by roobiniano** [comment]
> `include` is based on the path to the views folder, so the above line will look for the file views/template-parts/header.html - is that where the file is located?

Hi Dave, yes, the files are there, the error was that I was including the files with relative paths, thank you very much!
