### ISSUE TITLE
Routing, how to send string argument to controller in url 

### ISSUE THREAD

**Issue by roobiniano** [daveh/php-mvc#95]
Hi Dave, how are you?

I'm trying to send a string as an argument in the url and I can't get it to work. 
I've been looking at the Core\Routes file but can't find the way, 

I tried modifying the data type of the url in the router:

`admin/ajax/detail/{id:\%s}`
or
`admin/ajax/detail/{id:\s}`
or 
`admin/ajax/detail/{id:\s+}`

is there any way to receive a string id as an argument?

regards

**Comment by roobiniano** [comment]
also trying this 

`admin/ajax/detail/{id:[^a-zA-Z0-9-]+/}'`

**Comment by daveh** [comment]
Please can you give me an example of a URL you'd like to match (or the string you want to pass in the URL)?

**Comment by roobiniano** [comment]
> Please can you give me an example of a URL you'd like to match (or the string you want to pass in the URL)?

`/admin/ajax/detail/202105-025`

**202105-025** is the string id

**Comment by daveh** [comment]
`admin/ajax/detail/{id:[\d-]+}` will match that - `[\d-]` is a group containing digits and the hyphen character

**Comment by roobiniano** [comment]
thank you so much Dave, it worked perfect
