### ISSUE TITLE
Dynamic route URL 

### ISSUE THREAD

**Issue by Thlenzi** [daveh/php-mvc#97]
Hi! The standard route settings are based in this:
`$router->add('', ['controller' => 'Home', 'action' => 'index']);
$router->add('posts/index', ['controller' => 'Posts', 'action' => 'index']);`

@daveh , how can i set the route for dynamic url like: @*,  domain.com/@foo, domain.com/@bar ... ???

Have a nice day!

**Comment by daveh** [comment]
I'm not sure what you mean - you can have variables in the route, which can map to the controller and action - have a look at the readme [here](https://github.com/daveh/php-mvc#routing).

**Comment by Thlenzi** [comment]
@daveh , i find a solution in base this your awnser. [`link`](https://github.com/daveh/php-mvc/issues/70#issuecomment-715072063)
